### ISSUE TITLE
HTTP error code 0

### ISSUE THREAD

**Issue by eternal-sorrow** [lwindolf/liferea#260] opened 2015-10-07 11:29 UTC
From some moment I always get this error when trying to update any feed in my list.

**Comment by BillDietrich** [comment] 2020-02-06 12:06
I'm using Liferea 1.12.2 on Linux Mint 19.3.

I have several feeds that come from https://www.cbc.ca/podcasting/  They all behave the same, but take https://www.cbc.ca/podcasting/includes/ideas.xml as the example.

This feed fails validation on multiple services except the most lenient.  See:

https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.cbc.ca%2Fpodcasting%2Fincludes%2Fideas.xml

https://castfeedvalidator.com/?url=https://www.cbc.ca/podcasting/includes/ideas.xml

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.cbc.ca%2Fpodcasting%2Fincludes%2Fideas.xml

https://podba.se/validate/?url=https://www.cbc.ca/podcasting/includes/ideas.xml

When I add this feed to Liferea with source as URL, I get:

    The last update of this subscription failed!
    HTTP error code 0: There was an internal error in the update process
 
Please give a better error message.

If I use a browser to download https://www.cbc.ca/podcasting/includes/ideas.xml and save it to disk, then add this feed to Liferea with source as local file, the feed works perfectly !  No errors, no complaints, all the items appear.  But of course the feed will not update, unless I download the XML file to disk again every week or month or whatever.

Why would the XML file fail when source = URL, but succeed when source = local file ?  Is Liferea not using the DTD when source = local file ?  Or is there some effect of User Agent setting or something when downloading from URL ?

If not using the DTD is making the feed work (when source = local file), please add an option to not use DTD when source = URL.  Thanks.

**Comment by rich-coe** [comment] 2020-02-14 20:33
I don't know what @eternal-sorrow error (the details don't describe the issue) has to do with @BillDietrich issue, but I reproduced @BillDietrich issue with liferea-1.13.0 (from source).

    liferea makes a successful connection via TLS to ww.cbc.ca
    TLS is successfully negoitated
    liferea writes request
    www.cbc.ca returns a result
    TCP ack returned to www.cbc.ca 
    www.cbc.ca at the TCP level returns 'malformed packet'
    after several TCP re-transmissions, www.cbc.ca drops the connection

I made the same request with wget, and there are no TCP errors.
I don't know if there is a better error message since the transport layer is failing.
I suppose something in the libsoup layer may be causing an issue, but it will take more diagnosis to find the issue.
It would be helpful if it worked sometime in the past to find what is broken.

**Comment by nekohayo** [comment] 2020-03-26 21:34
Interestingly I'm encountering the same error with https://rss.cbc.ca/lineup/topstories.xml found on https://www.cbc.ca/rss/ ; issue #721 mentioned an interesting workaround: telling Liferea to use a custom command as the source instead of the URL, for example:

`wget --output-document=- --quiet https://rss.cbc.ca/lineup/topstories.xml`

Now the big question is, what can Liferea do to parse this correctly without needing to know about needing to use some external command to download the feed? As a comparison point, I tried out [FeedReader](https://www.flathub.org/apps/details/org.gnome.FeedReader) and that app was able to parse the feed from the URL without problems, indicating that it should be possible in theory.

**Comment by BillDietrich** [comment] 2020-03-27 22:12
The wget command worked in Liferea for me.  Thanks !

**Comment by lwindolf** [comment] 2020-12-15 22:13
Ticket cleanup. Closing old tickets.

**Closed by lwindolf** 2020-12-15 22:13 UTC

**Comment by kghenderson** [comment] 2021-01-19 20:44
why is this ticket closed? i'm also getting this issue

**Comment by rich-coe** [comment] 2021-01-21 16:34
@kghenderson What's the url of the feed that's failing?

**Comment by kghenderson** [comment] 2021-01-21 16:55
hmm ... well, I just switched back from Fedora Silverblue back to Fedora Workstation, and here the wget command works (which did not on Silverblue - perhaps wget was not available from the flatpak) ... this was for the same CBC feeds. Thanks for responding :-)
