### ISSUE TITLE
#570 not fully fixed, please reopen

### ISSUE THREAD

**Issue by heynnema** [lwindolf/liferea#590] opened 2018-01-09 20:35 UTC
@lwindolf 1.12.1 is an improvement, but it still doesn't fully remember the exact placement of the pane separator across restarts.

**Comment by lwindolf** [comment] 2018-05-01 21:53
Sorry for there being no solution yet, I did some extensive debugging, by adding outputting pane positions directly after they are set, and found they are no the same, so e.g. I set a pane to 100 and then fetch the position and get something like 80. This causes the problem over the restarts :-(

**Comment by lwindolf** [comment] 2018-08-18 10:04
Just to give an update on this: I have 100% no clue how to fix this, or why this actually happens :-(

**Comment by Leiaz** [comment] 2018-08-22 15:34
I think we have to choose between restoring the position or having both panels resize, for now. This looks like a Gtk issue to me.

**Comment by lwindolf** [comment] 2018-08-27 09:39
Brrr....

**Comment by nekohayo** [comment] 2020-03-30 03:28
I'm 99% sure this is actually not a Liferea bug, nor @lwindolf's fault, because I've encountered the same nonsense in Pitivi before, and it turns out to be a bug in GTK that was never fixed, this one I believe: https://bugzilla.gnome.org/show_bug.cgi?id=733638 (which might have gotten re-filed recently by someone else as https://gitlab.gnome.org/GNOME/gtk/-/issues/1959)

So if that's indeed the issue you are seeing... You might as well close all related issues in Liferea and point them to the upstream GTK bug(s) and subscribe there.

**Comment by Leiaz** [comment] 2020-10-15 16:55
Duplicate of #901

**Closed by Leiaz** 2020-10-15 16:55 UTC
Labels: bug
