### ISSUE TITLE
Cannot view images from some sites, TLS certificate failure

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#838] opened 2020-06-08 20:08 UTC
If I try to view the image in a post, or in a tab at this link
https://bunniefoo.com/ntw/ntw_may_2020a.jpg
It will not display.  In the tab, I get 'Unacceptable TLS certificate'.
If I display it with FF or Chrome, it works.
Does liferea or webkit have it's own cache of certs?

**Comment by rich-coe** [comment] 2020-06-08 20:24
% echo "" | openssl s_client   -connect bunniefoo.com:443
    depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
    verify return:1
    depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
    verify return:1
    depth=0 OU = Domain Control Validated, OU = Hosted by pair Networks, OU = COMODO SSL, CN = www.bunniefoo.com
    verify return:1
    CONNECTED(00000003)
    ---
    Certificate chain
     0 s:OU = Domain Control Validated, OU = Hosted by pair Networks, OU = COMODO SSL, CN = www.bunniefoo.com
       i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
     1 s:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
       i:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
     2 s:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
       i:C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    [ .... ]
    -----END CERTIFICATE-----
    subject=OU = Domain Control Validated, OU = Hosted by pair Networks, OU = COMODO SSL, CN = www.bunniefoo.com
    issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA

    ---
    No client certificate CA names sent
    Peer signing digest: SHA256
    Peer signature type: RSA
    Server Temp Key: ECDH, P-256, 256 bits
    ---
    SSL handshake has read 5361 bytes and written 441 bytes
    Verification: OK
    ---
    New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES256-GCM-SHA384
        Session-ID: BD44FFF567A4E7F3E6D330599E1B731E1B1BDA867EF4687AABFC65F4CB7AAACA
        Session-ID-ctx: 
        Master-Key: FD65FDE9AC89C685DAE6B08A237CD79A8CFC558BD32E1CD8DFB34D13AE0E5EB51EA682A1F41B6C28D70F3032D55656AE
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        TLS session ticket lifetime hint: 300 (seconds)
        TLS session ticket:
        0000 - 9d 9e 0f d7 af cb 32 71-d3 e0 ae a3 7a 29 dc a8   ......2q....z)..
        0010 - 6c 40 e4 01 d7 e1 f5 68-33 c5 eb 3d e9 fc 11 a0   l@.....h3..=....
        0020 - b4 c7 13 a9 a3 15 e3 ef-83 f5 7c 21 a0 0a ce e2   ..........|!....
        0030 - 5c c9 a7 8e ef 20 d5 5d-3a b8 85 ae a4 fa ed 0c   \.... .]:.......
        0040 - f9 17 0a 51 ca 80 03 74-b7 0a f4 73 d3 68 c2 73   ...Q...t...s.h.s
        0050 - 6f ad 98 c3 7d 34 8c 26-2a 6f cd c1 9a 15 c0 83   o...}4.&*o......
        0060 - 12 4d c3 c7 79 a5 71 66-a0 cc 95 a0 34 7b 28 2d   .M..y.qf....4{(-
        0070 - 5e 81 e1 d1 70 ca f9 f5-85 88 0e 4f 26 86 71 3a   ^...p......O&.q:
        0080 - 83 77 79 d3 f5 c3 12 dd-29 b6 73 a1 69 36 63 a4   .wy.....).s.i6c.
        0090 - 62 c4 b9 9d f8 48 67 92-15 b2 c8 4a 4c 52 ac 24   b....Hg....JLR.$
        00a0 - 11 66 55 40 d8 86 ed 4f-93 9d 1b 14 b6 a7 a3 c2   .fU@...O........
        00b0 - 09 a8 d0 6a 02 cd 13 b4-ce 81 88 0e 8f 0c f7 ba   ...j............
        00c0 - cf 29 dc 5a d8 32 ce fd-e2 29 68 85 4d a7 98 f7   .).Z.2...)h.M...

        Start Time: 1591647673
        Timeout   : 7200 (sec)
        Verify return code: 0 (ok)
        Extended master secret: no
    ---
    DONE

**Comment by Leiaz** [comment] 2020-06-09 14:54
I can't reproduce, using Debian testing.
Liferea doesn't change WebKit's default for certs.
You can try to open it in Epiphany to check if the issue comes from your system's WebKitGTK package.

**Comment by rich-coe** [comment] 2020-06-09 18:08
@leiaz If fails in epiphany too.  I'll try tracing it to find where it hides it's certs.

**Comment by rich-coe** [comment] 2020-06-09 18:22
I'm getting

    This Connection is Not Secure
    Technical information
    This website’s identification is too old to trust. Check the date on your computer’s calendar.

**Comment by rich-coe** [comment] 2020-06-09 18:37
epiphany is using the system's /var/lib/ca-certificates/
Using firefox to view the site certificate shows that the site cert has a date from Oct 2019 to Nov 2021.
I'm not sure what epiphany is complaing about with respect to computer time.

**Comment by lwindolf** [comment] 2020-06-13 17:30
The Qualys SSLLabs scanner shows the issue
https://www.ssllabs.com/ssltest/analyze.html?d=bunniefoo.com&s=210.23.25.55&latest

The certificate is ok, but the CA is not. It is expired. Here is media coverage on this
https://www.ssl.com/blogs/addtrust-external-ca-root-expired-may-30-2020/

The article also describe a workaround for webmasters affected by this.

Won't fix in Liferea or any other Webkit client :-(

**Closed by lwindolf** 2020-06-13 17:30 UTC

**Comment by rich-coe** [comment] 2020-06-13 19:40
epiphany/webkit is the only 'browser' with this issue.
Tested with fiefox, chrome, qutebrowser, IE11!, and edge.

**Comment by lwindolf** [comment] 2020-06-13 20:32
Hmm... Qualys actually reports 1 certificate path out of 3 being broken
![grafik](https://user-images.githubusercontent.com/3315368/84578461-b11f4300-adc5-11ea-8952-b7e1d63c308e.png)

Might be that the other browsers handle this better then Webkit.

Still nothing that can be done from Liferea project pov.
