### ISSUE TITLE
Prevent erroneous "Mark all as read"

### ISSUE THREAD

**Issue by Mno-hime** [lwindolf/liferea#32] opened 2014-06-01 12:31 UTC
I have a search folder for all unread items and the other day I erroneously marked it as read (hit Ctrl-R instead of Ctrl-U).. I'd lost the list if not having a yesterday's backup of Liferea's DB.

Can it be prevented in some way? Undo function would be nice but some non-intrusive confirmation dialogue would work for me as well.

**Comment by Mno-hime** [comment] 2015-02-10 11:01
Disabling Ctrl-R accelerator as per recent blog trick helped me a lot.

**Comment by gusnan** [comment] 2015-04-12 10:50
I have the same problem, but when right-clicking the channel name and aim for Update Folder, I some times (too often) by mistake hit the "Mark All as Read" menu item just below. Either moving the "Mark All as read" item, or as Mno-hime mentioned, making a confirmation dialog on the "Mark all as read item" would solve the problem.

**Comment by lwindolf** [comment] 2015-04-16 18:59
As a first solution I moved the menu option in the popup menu. Depending on the menu composition (as some items are optional according to the node type selected) the "Mark All Read" option is now in the middle. As in minimalistic menus (read-only sources) "Update" might still be above "Mark All Read" I additionally added a menu separator.

As for the hotkey I also fall victim for it from time to time.

I think I'll change Ctrl-R to refreshing the web view and assigning an entirely new accelerator for "Mark All as Read". I'm not yet sure which though...

**Comment by gusnan** [comment] 2015-04-16 19:18
Excellent! - I just compiled the git version, and it looks like a good solution for my menu problems. Much appreciated!

**Comment by GreenLunar** [comment] 2015-12-17 12:24
Related to #228

**Comment by voidplayer** [comment] 2016-09-06 10:47
today i clicked mark all as read instead of update feed... again...

solutions that comes to mind:

* Is it possible to change the color of the icon? both being green and both having some kind of pointy design does not help

* some confirmation dialog would be great as well. How often do you want to mark all as read, anyway? once per session as maximum. It is not very tedious to do, and prevent you from doing one of the worst mistakes you can do related to feed reader

* undo mark all as read. There is no need to implement some complete undo action for everything, only to remember the last state when you click mark all as read

Thanks for considering!

**Comment by dxwc** [comment] 2018-01-05 04:29
Same here. Just accidentally clicked 'Mark Items as Read' on a large folder while trying to add a new subscription there. Don't know much C to add a patch for myself. Do consider this issue if possible for future updates/release.

(Version 1.12.0 on Solus 3.26.2)

**Comment by lwindolf** [comment] 2018-03-07 19:57
An update on this topic: The next release will have an confirmation dialog.

Closing this as a duplicate of the newer discussion in #591

**Closed by lwindolf** 2018-03-07 19:57 UTC
