### ISSUE TITLE
Please add a safety question when "marking all as read"

### ISSUE THREAD

**Issue by Nudin** [lwindolf/liferea#591] opened 2018-01-11 13:59 UTC
I often accidentally click on "mark all a read". Since I often leaf interesting things marked as unread until I have time to read them this is a real issue for me, because I loose all the information which articles I still wanted to read.
Please add a security question "Are you sure you want to mark all news a read?" (with a checkbox, to not ask again).

**Comment by lwindolf** [comment] 2018-01-17 16:34
As there are a lot of reports like yours I think it's time to implement a confirmation dialog.

**Comment by da2x** [comment] 2018-01-21 11:03
Related or duplicate of #32.

**Comment by headsign** [comment] 2018-03-08 12:59
Thanks

**Comment by Leiaz** [comment] 2018-04-29 16:51
@lwindolf I just noticed there is a due date on the milestone. Do you want to write this ? (You assigned to yourself) Otherwise I can do it.

**Closed** 2018-05-01 21:48 UTC
Labels: enhancement

**Comment by lwindolf** [comment] 2018-05-01 21:51
@Leiaz I just found no time. Thanks for taking over!!!
