### ISSUE TITLE
Restore welcome screen

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#236] opened 2015-08-13 20:56 UTC
Add a preference in one of these forms:

Drop-down menu:
```
When Liferea starts: Continue from last session
                     Show welcome screen
```

Checkbox:
`Select last item when Liferea starts` (I need to rephrase it)
`Continue where I left`

**Comment by lwindolf** [comment] 2015-08-13 21:17
That's a feature request. Closing the ticket due to the "no feature request" policy.

**Closed by lwindolf** 2015-08-13 21:17 UTC

**Comment by GreenLunar** [comment] 2015-08-13 21:26
This is a bug, not a feature request.

Even on fresh install, the welcome screen is not shown, there is a funny layout instead.

**Comment by lwindolf** [comment] 2015-08-13 21:39
You ask for a preference. This is definitively an enhancement. 

I also see that you disagree with the removal of the welcome screen. Still it is not a bug that it was removed. It was intentionally removed. No regression here.

**Comment by GreenLunar** [comment] 2015-08-13 21:41
I would like to have it restored and being displayed at Liferea startup, without a preference as suggested above.

**Comment by lwindolf** [comment] 2015-08-13 21:44
I totally understand you wish. Still my decision was and still is to remove the welcome screen.

There is no bug here.

**Comment by GreenLunar** [comment] 2015-08-14 06:33
I think you should restore and improve the welcome screen.  There are many shiny CSS tricks you can utilize with CSS3 and HTNL5 and may give a good impression on new users.

**Comment by GreenLunar** [comment] 2015-08-21 07:30
From where can I download Liferea version 1.10-RC4?
