### ISSUE TITLE
Segmentation fault upon attempting to delete feed

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#246] opened 2015-08-26 15:27 UTC
Start Liferea with `liferea --add-feed %U --debug-all`.
Delete selected (newly added) feed.
Crash.

```
DB     : loading of itemset finished
DB     : loading itemset for node "jmgjjpo"
DB     : loading of itemset finished
DB     : loading itemset for node "ohmwdbk"
DB     : loading of itemset finished
DB     : loading itemset for node "lionnsa"
DB     : loading of itemset finished
DB     : loading itemset for node "avvefpf"
DB     : loading of itemset finished
DB     : loading itemset for node "bgmsutt"
DB     : loading of itemset finished
DB     : loading itemset for node "gvjigko"
DB     : loading of itemset finished
DB     : loading itemset for node "iefgvwc"
DB     : loading of itemset finished
DB     : loading itemset for node "lnmvsoq"
DB     : loading of itemset finished
DB     : loading itemset for node "wxisybe"
DB     : loading of itemset finished
DB     : loading itemset for node "cpotkqj"
DB     : loading of itemset finished
DB     : loading itemset for node "lhwoxlp"
DB     : loading of itemset finished
DB     : loading itemset for node "uxxcsgi"
DB     : loading of itemset finished
DB     : loading itemset for node "exhyhpa"
DB     : loading of itemset finished
DB     : loading itemset for node "lwicoue"
DB     : loading of itemset finished
DB     : loading itemset for node "wymxley"
DB     : loading of itemset finished
DB     : loading itemset for node "ppfavdx"
DB     : loading of itemset finished
DB     : loading itemset for node "sgomjja"
DB     : loading of itemset finished
DB     : loading itemset for node "uuarolb"
DB     : loading of itemset finished
DB     : loading itemset for node "rheolrp"
DB     : loading of itemset finished
DB     : loading itemset for node "owldexr"
DB     : loading of itemset finished
DB     : loading itemset for node "yqhrgft"
DB     : loading of itemset finished
DB     : loading itemset for node "xlcsuua"
DB     : loading of itemset finished
DB     : loading itemset for node "udffefd"
DB     : loading of itemset finished
DB     : loading itemset for node "micydoj"
DB     : loading of itemset finished
DB     : loading itemset for node "rydqsdd"
DB     : loading of itemset finished
DB     : loading itemset for node "eksxcje"
DB     : loading of itemset finished
DB     : loading itemset for node "casorhv"
DB     : loading of itemset finished
DB     : loading itemset for node "myguglm"
DB     : loading of itemset finished
DB     : loading itemset for node "jhsriwu"
DB     : loading of itemset finished
DB     : loading itemset for node "auhcmvx"
DB     : loading of itemset finished
DB     : loading itemset for node "hdnrcij"
DB     : loading of itemset finished
DB     : loading itemset for node "xluplxt"
DB     : loading of itemset finished
DB     : loading itemset for node "wasyvfx"
DB     : loading of itemset finished
DB     : loading itemset for node "hbleasw"
DB     : loading of itemset finished
DB     : loading itemset for node "nwflndw"
DB     : loading of itemset finished
DB     : loading itemset for node "hvqcdyk"
DB     : loading of itemset finished
DB     : loading itemset for node "jvdiaof"
DB     : loading of itemset finished
DB     : loading itemset for node "wjocqii"
DB     : loading of itemset finished
DB     : loading itemset for node "tgypkld"
DB     : loading of itemset finished
DB     : loading itemset for node "uvnfgdw"
DB     : loading of itemset finished
DB     : loading itemset for node "rbvulvo"
DB     : loading of itemset finished
DB     : loading itemset for node "xtpvxbo"
DB     : loading of itemset finished
DB     : loading itemset for node "okooign"
DB     : loading of itemset finished
DB     : loading itemset for node "fiesfbe"
DB     : loading of itemset finished
DB     : loading itemset for node "tbcobrh"
DB     : loading of itemset finished
GUI    : reloading item list with node "git.xfce.org"
DB     : loading item 77120
DB     : loading item 77121
DB     : loading item 77122
DB     : loading item 77123
DB     : loading item 77124
DB     : loading item 77125
DB     : loading item 77126
DB     : loading item 77127
DB     : loading item 77128
DB     : loading item 77129
DB     : loading item 93859
DB     : loading item 77170
DB     : loading item 77171
DB     : loading item 77172
DB     : loading item 77173
DB     : loading item 77174
DB     : loading item 77175
DB     : loading item 77176
DB     : loading item 77177
DB     : loading item 77178
DB     : loading item 77179
DB     : loading item 84448
DB     : loading item 84449
DB     : loading item 77130
DB     : loading item 77131
DB     : loading item 77132
DB     : loading item 77133
DB     : loading item 77134
DB     : loading item 77135
DB     : loading item 77136
DB     : loading item 77137
DB     : loading item 77138
DB     : loading item 77139
DB     : loading item 84143
DB     : loading item 84450
DB     : loading item 87000
DB     : loading item 89549
DB     : loading item 77140
DB     : loading item 77141
DB     : loading item 77142
DB     : loading item 77143
DB     : loading item 77144
DB     : loading item 77145
DB     : loading item 77146
DB     : loading item 77147
DB     : loading item 77148
DB     : loading item 77149
DB     : loading item 93860
DB     : loading item 77150
DB     : loading item 77151
DB     : loading item 77152
DB     : loading item 77153
DB     : loading item 77154
DB     : loading item 77155
DB     : loading item 77156
DB     : loading item 77157
DB     : loading item 77158
DB     : loading item 77159
DB     : loading item 82486
DB     : loading item 84451
DB     : loading item 96510
DB     : loading item 77160
DB     : loading item 77161
DB     : loading item 77162
DB     : loading item 77163
DB     : loading item 77164
DB     : loading item 77165
DB     : loading item 77166
DB     : loading item 77167
DB     : loading item 77168
DB     : loading item 77169
DB     : loading item 93861
DB     : loading item 77180
DB     : loading item 77181
DB     : loading item 77182
DB     : loading item 77183
DB     : loading item 77184
DB     : loading item 77185
DB     : loading item 77186
DB     : loading item 77187
DB     : loading item 77188
DB     : loading item 77189
DB     : loading item 77190
DB     : loading item 77191
DB     : loading item 77192
DB     : loading item 77193
DB     : loading item 77194
DB     : loading item 77195
DB     : loading item 77196
DB     : loading item 77197
DB     : loading item 77198
DB     : loading item 77199
DB     : loading item 78537
DB     : loading item 77200
DB     : loading item 77201
DB     : loading item 77202
DB     : loading item 77203
DB     : loading item 77204
DB     : loading item 77205
DB     : loading item 77206
DB     : loading item 77207
DB     : loading item 77208
DB     : loading item 77209
DB     : loading item 77210
DB     : loading item 77211
DB     : loading item 77212
DB     : loading item 77213
DB     : loading item 77214
DB     : loading item 77215
DB     : loading item 77216
DB     : loading item 77217
DB     : loading item 77218
DB     : loading item 77219
DB     : loading item 77220
DB     : loading item 77221
DB     : loading item 77222
DB     : loading item 77223
DB     : loading item 77224
DB     : loading item 77225
DB     : loading item 77226
DB     : loading item 77227
DB     : loading item 77228
DB     : loading item 77229
DB     : loading item 78538
DB     : loading item 84452
DB     : loading item 92894
DB     : loading item 77230
DB     : loading item 77231
DB     : loading item 77232
DB     : loading item 77233
DB     : loading item 77234
DB     : loading item 77235
DB     : loading item 77236
DB     : loading item 77237
DB     : loading item 77238
DB     : loading item 77239
DB     : loading item 79106
DB     : loading item 84453
DB     : loading item 93862
DB     : loading item 77240
DB     : loading item 77241
DB     : loading item 77242
DB     : loading item 77243
DB     : loading item 77244
DB     : loading item 77245
DB     : loading item 77246
DB     : loading item 77247
DB     : loading item 77248
DB     : loading item 77249
DB     : loading item 78249
DB     : loading item 78539
DB     : loading item 79839
DB     : loading item 81822
DB     : loading item 77250
DB     : loading item 77251
DB     : loading item 77252
DB     : loading item 77253
DB     : loading item 77254
DB     : loading item 77255
DB     : loading item 77256
DB     : loading item 77257
DB     : loading item 77258
DB     : loading item 77259
DB     : loading item 89550
DB     : loading item 98672
DB     : loading item 77260
DB     : loading item 77261
DB     : loading item 77262
DB     : loading item 77263
DB     : loading item 77264
DB     : loading item 77265
DB     : loading item 77266
DB     : loading item 77267
DB     : loading item 77268
DB     : loading item 77269
DB     : loading item 93863
DB     : loading item 93995
DB     : loading item 93996
DB     : loading item 93997
DB     : loading item 93998
DB     : loading item 93999
DB     : loading item 94000
DB     : loading item 94001
DB     : loading item 94002
DB     : loading item 94003
DB     : loading item 94004
DB     : loading item 94015
DB     : loading item 94016
DB     : loading item 94017
DB     : loading item 94018
DB     : loading item 94019
DB     : loading item 94020
DB     : loading item 94021
DB     : loading item 94022
DB     : loading item 94023
DB     : loading item 94024
DB     : loading item 94025
DB     : loading item 94026
DB     : = item load took 0,005s
DB     : loading item 94027
DB     : loading item 94028
DB     : loading item 94029
DB     : loading item 94030
DB     : loading item 94031
DB     : loading item 94032
DB     : loading item 94033
DB     : loading item 94034
DB     : loading item 94035
DB     : loading item 94036
DB     : loading item 94037
DB     : loading item 94038
DB     : loading item 94039
DB     : loading item 94040
DB     : loading item 94041
DB     : loading item 94042
DB     : loading item 94043
DB     : loading item 94044
DB     : loading item 94045
DB     : loading item 94046
DB     : loading item 94047
DB     : loading item 94048
DB     : loading item 94049
DB     : loading item 94050
DB     : loading item 94051
DB     : loading item 94052
DB     : loading item 94053
DB     : loading item 94054
DB     : loading item 94055
DB     : loading item 94056
DB     : loading item 94057
DB     : loading item 94058
DB     : loading item 94059
DB     : loading item 94060
DB     : loading item 94061
DB     : loading item 94062
DB     : loading item 94063
DB     : loading item 94064
DB     : loading item 94065
DB     : loading item 94066
DB     : loading item 94067
DB     : loading item 94068
DB     : loading item 94069
DB     : loading item 94070
DB     : loading item 94071
DB     : loading item 94072
DB     : loading item 94073
DB     : loading item 94074
DB     : loading item 94075
DB     : loading item 94076
DB     : loading item 94077
DB     : loading item 94078
DB     : loading item 94079
DB     : loading item 94080
DB     : loading item 94081
DB     : loading item 94082
DB     : loading item 94083
DB     : loading item 94084
DB     : loading item 94085
DB     : loading item 94086
DB     : loading item 94087
DB     : loading item 94088
DB     : loading item 94089
DB     : loading item 94090
DB     : loading item 94091
DB     : loading item 94092
DB     : loading item 94093
DB     : loading item 94094
DB     : loading item 94095
DB     : loading item 94096
DB     : loading item 94097
DB     : loading item 94098
DB     : loading item 94099
DB     : loading item 94100
DB     : loading item 94101
DB     : loading item 94102
DB     : loading item 94103
DB     : loading item 94104
DB     : loading item 94105
DB     : loading item 94106
DB     : loading item 94107
DB     : loading item 94108
DB     : loading item 94109
DB     : loading item 94110
DB     : loading item 94111
DB     : loading item 94112
DB     : loading item 94113
DB     : loading item 94114
DB     : loading item 98673
DB     : loading item 94125
DB     : loading item 94126
DB     : loading item 94127
DB     : loading item 94128
DB     : loading item 94129
DB     : loading item 94130
DB     : loading item 94131
DB     : loading item 94132
DB     : loading item 94133
DB     : loading item 94134
DB     : loading item 94145
DB     : loading item 94146
DB     : loading item 94147
DB     : loading item 94148
DB     : loading item 94149
DB     : loading item 94150
DB     : loading item 94151
DB     : loading item 94152
DB     : loading item 94153
DB     : loading item 94154
DB     : loading item 98547
DB     : loading item 98548
DB     : loading item 98549
DB     : loading item 94163
DB     : loading item 94164
DB     : loading item 94165
DB     : loading item 94166
DB     : loading item 94167
DB     : loading item 94168
DB     : loading item 94169
DB     : loading item 94170
DB     : loading item 94171
DB     : loading item 94172
DB     : loading item 94187
DB     : loading item 94188
DB     : loading item 94189
DB     : loading item 94190
DB     : loading item 94191
DB     : loading item 94192
DB     : loading item 94193
DB     : loading item 94194
DB     : loading item 94195
DB     : loading item 94196
DB     : loading item 94200
DB     : loading item 94201
DB     : loading item 94202
DB     : loading item 94203
DB     : loading item 94204
DB     : loading item 94205
DB     : loading item 94206
DB     : loading item 94207
DB     : loading item 94208
DB     : loading item 94209
DB     : loading item 94210
DB     : loading item 94211
DB     : loading item 94212
DB     : loading item 94213
DB     : loading item 94214
DB     : loading item 94215
DB     : loading item 94216
DB     : loading item 94217
DB     : loading item 94218
DB     : loading item 94219
DB     : loading item 98674
DB     : loading item 94220
DB     : loading item 94221
DB     : loading item 94222
DB     : loading item 94223
DB     : loading item 94224
DB     : loading item 94225
DB     : loading item 94226
DB     : loading item 94227
DB     : loading item 94228
DB     : loading item 94229
DB     : loading item 94230
DB     : loading item 94231
DB     : loading item 94232
DB     : loading item 94233
DB     : loading item 94234
DB     : loading item 94235
DB     : loading item 94236
DB     : loading item 94237
DB     : loading item 94238
DB     : loading item 94239
DB     : loading item 94240
DB     : loading item 94241
DB     : loading item 94242
DB     : loading item 94243
DB     : loading item 94244
DB     : loading item 94245
DB     : loading item 94246
DB     : loading item 94247
DB     : loading item 94248
DB     : loading item 94249
DB     : loading item 94250
DB     : loading item 94251
DB     : loading item 94252
DB     : loading item 94253
DB     : loading item 94254
DB     : loading item 94255
DB     : loading item 94256
DB     : loading item 94257
DB     : loading item 94258
DB     : loading item 94259
DB     : loading item 94263
DB     : loading item 94264
DB     : loading item 94265
DB     : loading item 94266
DB     : loading item 94267
DB     : loading item 94268
DB     : loading item 94269
DB     : loading item 94270
DB     : loading item 94271
DB     : loading item 94272
DB     : loading item 94273
DB     : loading item 94274
DB     : loading item 94275
DB     : loading item 94276
DB     : loading item 94277
DB     : loading item 94278
DB     : loading item 94279
DB     : loading item 94280
DB     : loading item 94281
DB     : loading item 94282
DB     : loading item 94283
DB     : loading item 94284
DB     : loading item 94285
DB     : loading item 94286
DB     : loading item 94287
DB     : loading item 94288
DB     : loading item 94289
DB     : loading item 94290
DB     : loading item 94291
DB     : loading item 94292
DB     : loading item 94293
DB     : loading item 94294
DB     : loading item 94295
DB     : loading item 94296
DB     : loading item 94297
DB     : loading item 94298
DB     : loading item 94299
DB     : loading item 94300
DB     : loading item 94301
DB     : loading item 94302
DB     : loading item 94313
DB     : loading item 94314
DB     : loading item 94315
DB     : loading item 94316
DB     : loading item 94317
DB     : loading item 94318
DB     : loading item 94319
DB     : loading item 94320
DB     : loading item 94321
DB     : loading item 94322
DB     : loading item 94323
DB     : = item load took 0,001s
DB     : loading item 94324
DB     : loading item 94325
DB     : loading item 94326
DB     : loading item 94327
DB     : loading item 94328
DB     : loading item 94329
DB     : loading item 94330
DB     : loading item 94331
DB     : loading item 94332
DB     : loading item 94333
DB     : loading item 94334
DB     : loading item 94335
DB     : loading item 94336
DB     : loading item 94337
DB     : loading item 94338
DB     : loading item 94339
DB     : loading item 94340
DB     : loading item 94341
DB     : loading item 94342
DB     : loading item 94343
DB     : loading item 94344
DB     : loading item 94345
DB     : loading item 94346
DB     : loading item 94347
DB     : loading item 94348
DB     : loading item 94349
DB     : loading item 94350
DB     : loading item 94351
DB     : loading item 94352
DB     : loading item 94353
DB     : loading item 94354
DB     : loading item 94355
DB     : loading item 94356
DB     : loading item 94357
DB     : loading item 94358
DB     : loading item 94359
DB     : loading item 94360
DB     : loading item 94361
DB     : loading item 94362
DB     : loading item 98675
DB     : loading item 94373
DB     : loading item 94374
DB     : loading item 94375
DB     : loading item 94376
DB     : loading item 94377
DB     : loading item 94378
DB     : loading item 94379
DB     : loading item 94380
DB     : loading item 94381
DB     : loading item 94382
DB     : loading item 94383
DB     : loading item 94384
DB     : loading item 94385
DB     : loading item 94386
DB     : loading item 94387
DB     : loading item 94388
DB     : loading item 94389
DB     : loading item 94390
DB     : loading item 94391
DB     : loading item 94392
DB     : loading item 94393
DB     : loading item 94394
DB     : loading item 94395
DB     : loading item 94396
DB     : loading item 94397
DB     : loading item 94398
DB     : loading item 94399
DB     : loading item 94400
DB     : loading item 94401
DB     : loading item 94402
DB     : loading item 94403
DB     : loading item 94404
DB     : loading item 94405
DB     : loading item 94406
DB     : loading item 94407
DB     : loading item 94408
DB     : loading item 94409
DB     : loading item 94410
DB     : loading item 94411
DB     : loading item 94412
DB     : loading item 94413
DB     : = item load took 0,001s
DB     : loading item 94414
DB     : loading item 94415
DB     : loading item 94416
DB     : loading item 94417
DB     : loading item 94418
DB     : loading item 94419
DB     : loading item 94420
DB     : loading item 94421
DB     : loading item 94422
DB     : loading item 94423
DB     : loading item 94424
DB     : loading item 94425
DB     : loading item 94426
DB     : loading item 94427
DB     : loading item 94428
DB     : loading item 94429
DB     : loading item 94430
DB     : loading item 94431
DB     : loading item 94432
DB     : loading item 94433
DB     : loading item 94434
DB     : loading item 94435
DB     : loading item 94436
DB     : loading item 94437
DB     : loading item 94438
DB     : loading item 94439
DB     : loading item 94440
DB     : loading item 94441
DB     : loading item 94442
DB     : loading item 94443
DB     : loading item 94444
DB     : loading item 94445
DB     : loading item 94446
DB     : loading item 94447
DB     : loading item 94448
DB     : loading item 94449
DB     : loading item 94450
DB     : loading item 94451
DB     : loading item 94452
DB     : loading item 94453
DB     : loading item 94454
DB     : loading item 94455
DB     : loading item 94456
DB     : loading item 94457
DB     : loading item 94458
DB     : loading item 94459
DB     : loading item 94460
DB     : loading item 94461
DB     : loading item 94462
DB     : loading item 94463
DB     : loading item 94464
DB     : loading item 94465
DB     : loading item 94466
DB     : loading item 94467
DB     : loading item 94468
DB     : loading item 94469
DB     : loading item 94470
DB     : loading item 94471
DB     : loading item 94472
DB     : loading item 94473
DB     : loading item 94474
DB     : loading item 94475
DB     : loading item 94476
DB     : loading item 94477
DB     : loading item 94478
DB     : loading item 94479
DB     : loading item 94480
DB     : loading item 94481
DB     : loading item 94482
DB     : loading item 94483
DB     : loading item 94484
DB     : loading item 94485
DB     : loading item 94486
DB     : loading item 94487
DB     : loading item 94488
DB     : loading item 94489
DB     : loading item 94490
DB     : loading item 94491
DB     : loading item 94492
DB     : loading item 94493
DB     : loading item 94494
DB     : loading item 94495
DB     : loading item 94496
DB     : loading item 94497
DB     : loading item 94498
DB     : loading item 94499
DB     : loading item 94500
DB     : loading item 94501
DB     : loading item 94502
DB     : loading item 94523
DB     : loading item 94503
DB     : loading item 94504
DB     : loading item 94505
DB     : loading item 94506
DB     : loading item 94507
DB     : loading item 94508
DB     : loading item 94509
DB     : loading item 94510
DB     : loading item 94511
DB     : loading item 94512
DB     : loading item 94513
DB     : loading item 94514
DB     : loading item 94515
DB     : loading item 94516
DB     : loading item 94517
DB     : loading item 94518
DB     : loading item 94519
DB     : loading item 94520
DB     : loading item 94521
DB     : loading item 94522
DB     : loading item 77270
DB     : loading item 77271
DB     : loading item 77272
DB     : loading item 77273
DB     : loading item 77274
DB     : loading item 77275
DB     : loading item 77276
DB     : loading item 77277
DB     : loading item 77278
DB     : loading item 77279
DB     : loading item 77280
DB     : loading item 77281
DB     : loading item 77282
DB     : loading item 77283
DB     : loading item 77284
DB     : loading item 77285
DB     : loading item 77286
DB     : loading item 77287
DB     : loading item 77288
DB     : loading item 77289
DB     : loading item 77290
DB     : loading item 77291
DB     : loading item 77292
DB     : loading item 77293
DB     : loading item 77294
DB     : loading item 77295
DB     : loading item 77296
DB     : loading item 77297
DB     : loading item 77298
DB     : loading item 77299
DB     : loading item 84220
DB     : loading item 77300
DB     : loading item 77301
DB     : loading item 77302
DB     : loading item 77303
DB     : loading item 77304
DB     : loading item 77305
DB     : loading item 77306
DB     : loading item 77307
DB     : loading item 77308
DB     : loading item 77309
DB     : loading item 77310
DB     : loading item 77311
DB     : loading item 77312
DB     : loading item 77313
DB     : loading item 77314
DB     : loading item 77315
DB     : loading item 77316
DB     : loading item 77317
DB     : loading item 77318
DB     : loading item 77319
DB     : loading item 84221
DB     : loading item 76973
DB     : loading item 76974
DB     : loading item 76975
DB     : loading item 76976
DB     : loading item 76977
DB     : loading item 76978
DB     : loading item 76979
DB     : loading item 76980
DB     : loading item 76981
DB     : loading item 76982
DB     : loading item 84222
DB     : loading item 98942
DB     : loading item 98943
DB     : loading item 76983
DB     : loading item 76984
DB     : loading item 76985
DB     : loading item 76986
DB     : loading item 76987
DB     : loading item 76988
DB     : loading item 76989
DB     : loading item 76990
DB     : loading item 76991
DB     : loading item 76992
DB     : loading item 76993
DB     : loading item 76994
DB     : loading item 76995
DB     : loading item 76996
DB     : loading item 76997
DB     : loading item 76998
DB     : loading item 76999
DB     : loading item 77000
DB     : loading item 77001
DB     : loading item 77002
DB     : loading item 77003
DB     : loading item 77004
DB     : loading item 77005
DB     : loading item 77006
DB     : loading item 77007
DB     : loading item 77008
DB     : loading item 77009
DB     : loading item 77010
DB     : loading item 77011
DB     : loading item 77012
DB     : loading item 77013
DB     : loading item 77014
DB     : loading item 77015
DB     : loading item 77016
DB     : loading item 77017
DB     : loading item 77018
DB     : loading item 77019
DB     : loading item 77020
DB     : loading item 77021
DB     : loading item 77022
DB     : loading item 77023
DB     : loading item 77024
DB     : loading item 77025
DB     : loading item 77026
DB     : loading item 77027
DB     : loading item 77028
DB     : loading item 77029
DB     : loading item 77030
DB     : loading item 77031
DB     : loading item 77032
DB     : loading item 84223
DB     : loading item 87001
DB     : loading item 89551
DB     : loading item 89552
DB     : loading item 77033
DB     : loading item 77034
DB     : loading item 77035
DB     : loading item 77036
DB     : loading item 77037
DB     : loading item 77038
DB     : loading item 77039
DB     : loading item 77040
DB     : loading item 77041
DB     : loading item 77042
DB     : loading item 77043
DB     : loading item 77044
DB     : loading item 77045
DB     : loading item 77046
DB     : loading item 77047
DB     : loading item 77048
DB     : loading item 77049
DB     : loading item 77050
DB     : loading item 77051
DB     : loading item 77052
DB     : loading item 77053
DB     : loading item 76777
DB     : loading item 76778
DB     : loading item 76779
DB     : loading item 76780
DB     : loading item 76781
DB     : loading item 76782
DB     : loading item 76783
DB     : loading item 76784
DB     : loading item 76785
DB     : loading item 76786
DB     : loading item 77320
DB     : loading item 87002
DB     : loading item 77054
DB     : loading item 77055
DB     : loading item 77056
DB     : loading item 77057
DB     : loading item 77058
DB     : loading item 77059
DB     : loading item 77060
DB     : loading item 77061
DB     : loading item 77062
DB     : loading item 77063
DB     : loading item 77064
DB     : loading item 77065
DB     : loading item 77066
DB     : loading item 77067
DB     : loading item 77068
DB     : loading item 77069
DB     : loading item 77070
DB     : loading item 77071
DB     : loading item 77072
DB     : loading item 77073
DB     : loading item 77074
DB     : loading item 77075
DB     : loading item 77076
DB     : loading item 77077
DB     : loading item 77078
DB     : loading item 77079
DB     : loading item 76767
DB     : loading item 76768
DB     : loading item 76769
DB     : loading item 76770
DB     : loading item 76771
DB     : loading item 76772
DB     : loading item 76773
DB     : loading item 76774
DB     : loading item 76775
DB     : loading item 76776
DB     : loading item 76971
DB     : loading item 78540
DB     : loading item 84224
DB     : loading item 91955
DB     : loading item 77080
DB     : loading item 77081
DB     : loading item 77082
DB     : loading item 77083
DB     : loading item 77084
DB     : loading item 77085
DB     : loading item 77086
DB     : loading item 77087
DB     : loading item 77088
DB     : loading item 77089
DB     : loading item 78250
DB     : loading item 77090
DB     : loading item 77091
DB     : loading item 77092
DB     : loading item 77093
DB     : loading item 77094
DB     : loading item 77095
DB     : loading item 77096
DB     : loading item 77097
DB     : loading item 77098
DB     : loading item 77099
DB     : loading item 78541
DB     : loading item 84225
DB     : loading item 84226
DB     : loading item 77100
DB     : loading item 77101
DB     : loading item 77102
DB     : loading item 77103
DB     : loading item 77104
DB     : loading item 77105
DB     : loading item 77106
DB     : loading item 77107
DB     : loading item 77108
DB     : loading item 77109
DB     : loading item 87003
DB     : loading item 77110
DB     : loading item 77111
DB     : loading item 77112
DB     : loading item 77113
DB     : loading item 77114
DB     : loading item 77115
DB     : loading item 77116
DB     : loading item 77117
DB     : loading item 77118
DB     : loading item 77119
DB     : loading item 78542
DB     : loading item 84227
DB     : loading item 87004
DB     : loading item 87005
DB     : loading item 87006
DB     : loading item 87007
DB     : loading item 96511
DB     : loading item 98303
DB     : loading item 76757
DB     : loading item 76758
DB     : loading item 76759
DB     : loading item 76760
DB     : loading item 76761
DB     : loading item 76762
DB     : loading item 76763
DB     : loading item 76764
DB     : loading item 76765
DB     : loading item 76766
DB     : loading item 76972
DB     : loading item 82487
DB     : loading item 84228
DB     : loading item 98304
DB     : loading item 98305
DB     : loading item 98306
DB     : loading item 98307
DB     : loading item 98308
DB     : loading item 98309
DB     : loading item 98310
HTML   : writing 1466 bytes to HTML view
GUI    : = itemlist merge took 0,194s
PERF   : = itemlist_merge_itemset took 0,194s
PERF   : = itemlist_load took 0,199s
PERF   : = feedlist_selection_changed took 0,199s
Segmentation fault
```

**Comment by lwindolf** [comment] 2015-10-30 23:17
As with all crashes: can you please provide a backtrace. This is a race condition that is not always reproducible, but I see it sometimes too.

**Comment by GreenLunar** [comment] 2015-10-31 18:42
> As with all crashes: can you please provide a backtrace.

How can I provide you with a backtrace?

**Comment by lwindolf** [comment] 2015-10-31 19:36
Using gdb. A short description can be found here http://lzone.de/liferea/faq.htm#too-much-crashes

**Comment by GreenLunar** [comment] 2015-11-01 19:09
```
$ gdb liferea core
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i486-slackware-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/liferea...(no debugging symbols found)...done.
/home/GreenLunar/core: No such file or directory.
(gdb) bt
No stack.
(gdb) 
```

**Comment by GreenLunar** [comment] 2015-11-02 03:42
I have a file of 85MB called *core*.  How would you like to receive it?

**Comment by genodeftest** [comment] 2015-11-21 13:34
@GreenLunar: please try running gdb on this file *core*. Something in `gdb liferea core` was wrong. Try `gdb liferea ./core` or something else to get the right path.

Since you can reproduce this issue you can alternatively run liferea from gdb: `gdb liferea`, then reproduce the issue and export a backtrace. Running `set logging on logging-filename.txt` will put all your logs in a text file so you don't have to copy them from terminal. You can add more information to the backtrace by running `thread apply all bt full` (or short `t a a bt full`). This will dump all threads and longer backtraces.

**Comment by mikelolasagasti** [comment] 2016-11-25 21:52
Works for me in master with Fedora 25. @GreenLunar can you reproduce?

**Comment by lwindolf** [comment] 2017-12-26 23:21
Closing this very old bug.

**Closed by lwindolf** 2017-12-26 23:21 UTC
Labels: bug, help-wanted
