### ISSUE TITLE
1.12-RC1: Once changed, headlines order can not be set back to chronological order

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#408] opened 2016-10-09 19:17 UTC
This is a straight copy of Debian bug 840233¹ that I just received:

¹ https://bugs.debian.org/840233

with this RC version it became impossible to change the order of
headlines back to chronological order once a user changes it by
clicking on the "Headline" labeled bar. Once clicked, it allows only to
toggle between alphabetical and reversed alphabetical order.

The only way I could find to get back chronological order is by
quitting liferea, editing $HOME/.config/liferea/feedlist.opml directly
and setting sortColumn="time" for the affected feed(s).

I know it's not a stable release of liferea, but maybe nobody happened
to stumble over this, yet.

**Comment by paulgevers** [comment] 2016-10-09 19:23
Just a comment from my side, this is not reproducible on my own computer, so I guess there is more involved here.

**Comment by lwindolf** [comment] 2018-01-17 17:26
This is fixed by redesign in 1.12.0.

Root cause was that in wide view (with the date column removed) headline sorting (in 1.12-RC1) was by title string, which caused the date order to be lost.

This was fixed with 1.12.0 by dropping the title sorting and sorting by date only.

**Closed by lwindolf** 2018-01-17 17:26 UTC
Labels: bug
