### ISSUE TITLE
tumblr sites don't update

### ISSUE THREAD

**Issue by ndias** [lwindolf/liferea#641] opened 2018-05-19 22:16 UTC
And when add new sites from  tumblr the feed never gets updated also

**Comment by rfc1036** [comment] 2018-05-20 00:38
This happens because now tumblr will redirect to a GDPR compliance page unless the right cookie (pfg) is provided. I am not sure about the best way to work around this since:
- the cookie contains an hash of the User-Agent header
- the cookie itself is signed, so it cannot be modified trivially

**Comment by jjpp** [comment] 2018-05-20 22:18
One can open the rss link (Source) on the error page using internal browser and accept the terms there (for me with external browser as a default -- "open in new tab" from right-click menu did the trick). The cookie seems to be remembered there (if I restart liferea, it does not ask again for acceptance). Can't you just reuse the same cookies?

**Comment by rfc1036** [comment] 2018-05-21 08:50
"Open in new tab" does not set the cookie on my system (I am using the 1.12.2 Debian package).

**Comment by Leiaz** [comment] 2018-05-21 16:49
@jjpp This won't work as the SoupSession downloading the feeds and the WebKitGtk browser don't use the same cookie jar.

They also don't use the same user agent.
The user agent for the SoupSession is in the form `Liferea/1.12.3 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)`.
If you can get the correct cookie(s?), it should be added to `~/.config/liferea/cookies.txt`

The functions to get the cookies from the WebKit2Gtk's cookie jar [were only added in version 2.20](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitCookieManager.html).

**Comment by jjpp** [comment] 2018-05-22 00:07
Hm. If the clients are different then this can't work indeed. It seems that tumblr expects JSON posted to https://www.tumblr.com/svc/privacy/consent 

Until someone figures out a better way.. 

1. Find out exact user agent your version uses. 
1.1. Start liferea
1.2. In a terminal, start `strace -e network -s 65534 -p $(pidof liferea) 2>&1 | grep Liferea/`
1.3. Try to update a http feed or add random http (not https!) url as a new subscription
1.4. In the terminal with strace, you should see lines like `sendto(35, "GET /news/index.rss HTTP/1.1\r\nHost: propellor.branchable.com\r\nIf-Modified-Since: Thu, 17 May 2018 14:47:02 GMT\r\nIf-None-Match: \"1d92-56c67e8882d21-gzip\"\r\nA-IM: feed\r\nAccept: application/atom+xml,application/xml;q=0.9,text/xml;q=0.8,*/*;q=0.7\r\nDNT: 1\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Liferea/1.12.2 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)\r\nConnection: Keep-Alive\r\n\r\n", 404, MSG_NOSIGNAL, NULL, 0) = 404`

2. Submit consent confirmation using curl. This will try to write to file for_liferea.txt in current directory. Also, please update User agent header with one seen in previous step, if needed. Submitted booleans were all true, originally. 
2.1. `curl -c for_liferea.txt -H 'Content-type: application/json' -H 'User-Agent: Liferea/1.12.2 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)' -d '{"eu_resident":true,"gdpr_is_acceptable_age":true,"gdpr_consent_core":true,"gdpr_consent_first_party_ads":false,"gdpr_consent_third_party_ads":false,"gdpr_consent_search_history":false,"redirect_to":"https://random.tumblr.com/rss"}' https://www.tumblr.com/svc/privacy/consent; echo`

3. Add saved cookies to liferea's cookie file:
3.1. Quit liferea, it seems that it only reads cookie file only once after starting up 
3.2. `cat for_liferea.txt >> ~/.config/liferea/cookies.txt`

4. Start liferea again, the feeds should be ok now. 

As the user agent contains version number and changing it seemed to make the cookie useless, one might need to repeat the whole process. Cookie expires in one year but tumblr seems to refresh it on every request, so that should not be a problem.

**Comment by bicobus** [comment] 2018-06-08 18:55
Follow up on @jjpp 's method.

It appears that tumblr added more parameters to the request (`X-tumblr-form-key`), and it seems now impossible to fix this thing with just a curl request. Tumblr returns a 'Request Denied' page. Beside, the user should read all that stuff as tumblr is now liable for whatever they do with our data.

**Comment by jjpp** [comment] 2018-06-09 20:45
Indeed. They also seem to hash in the presence of DNT: 1 header. 
So, for the brave ones:
`curl -c for_liferea.txt -H 'DNT: 1' -H "Referer: https://www.tumblr.com/privacy/consent?redirect=https%3A%2F%2Fdevopsreactions.tumblr.com%2Frss" -H "X-tumblr-form-key: `curl -s 'https://www.tumblr.com/privacy/consent?redirect=https://devopsreactions.tumblr.com/rss' | grep tumblr-form-key | sed -e 's/^.*form_key" content="//' -e 's/".*$//'`" -H 'Content-type: application/json' -H 'User-Agent: Liferea/1.12.3 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)' -d '{"eu_resident":true,"gdpr_is_acceptable_age":true,"gdpr_consent_core":true,"gdpr_consent_first_party_ads":true,"gdpr_consent_third_party_ads":true,"gdpr_consent_search_history":true,"redirect_to":"http://devopsreactions.tumblr.com/rss"}' https://www.tumblr.com/svc/privacy/consent; echo
`
And then you actually have to go to that page as a first thing with that cookie as well:
`curl -b for_liferea.txt -c for_liferea.txt -H 'DNT: 1' -H 'User-Agent: Liferea/1.12.3 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)' http://devopsreactions.tumblr.com/rss
`
You know you succeeded if you get RSS and not 302 redirect. If successful, kill liferea, edit ~/.config/liferea/cookies.txt (remove all lines that contain tumblr in the first column) and add the contents of for_liferea.txt . All of the tumblr blogs should be okay now. No idea, if there is a need to do it with https-link if your rss-urls are with https. 


About reading the consent before accepting it -- absolutely. But the other part is that after we have read it (in a browser, possibly), we would really like our RSS-readers to be able to do their thing as well. If tumblr needs a way to bind consent to the specific requester, then they could return a rss feed with just one item -- something that has a link to consent page, with parameter that allows them to identify the requester. And the consent page could (after the consent has been given) give back a link (possibly with a parameter) to be used in reader -- so instead of the cookie (that is awkward or impossible to add to the cookie store for a regular user), there could be a parameter with the same function. Or something to that effect.

**Comment by da2x** [comment] 2019-01-12 22:37
This is a deployment bug at Tumblr and not a bug with Liferea.

**Comment by ap** [comment] 2019-12-11 08:42
The GDPR redirect can be avoided by using a Googlebot user agent.
````
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
````

**Comment by lwindolf** [comment] 2019-12-23 13:49
@ap Great hint!

**Comment by nekohayo** [comment] 2021-01-10 21:28
Lars, I think you forgot to close this ticket?

**Comment by lwindolf** [comment] 2021-01-10 22:40
Yup. Can be closed.

**Closed by lwindolf** 2021-01-10 22:40 UTC
Labels: wontfix
