### ISSUE TITLE
v1.11.3 craches when updating all feeds

### ISSUE THREAD

**Issue by zloster** [lwindolf/liferea#152] opened 2015-02-16 16:24 UTC
I use Ubuntu 12.04. The code is compiled from the source tarball available here: https://github.com/lwindolf/liferea/releases/download/v1.11.3/liferea-1.11.3.tar.bz2 Here is the bt trace I gathered:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3f26c25 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff3f26c25 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff52528c8 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x00007ffff5254130 in gtk_tree_store_set_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff5254217 in gtk_tree_store_set () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x0000000000442a59 in feed_list_node_update (nodeId=<optimized out>) at feed_list_node.c:340
#5  0x0000000000421f68 in favicon_download_run (ctxt=0x10873b0) at favicon.c:242
#6  0x0000000000422191 in favicon_download_icon_cb (result=<optimized out>, user_data=0x10873b0, flags=<optimized out>)
    at favicon.c:185
#7  0x000000000042efba in update_process_result_idle_cb (user_data=<optimized out>) at update.c:568
#8  0x00007ffff3c64d13 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff3c65060 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff3c65124 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff4892dd4 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x0000000000419c2b in main (argc=1, argv=0x7fffffffe178) at main.c:258
(gdb) 
```
I observe the crashes in two cases:
1. The program is configured to update the feeds on start -> will crash;
2. I manually trigger the feeds update via the menu 'Subscriptions->Update all' -> will crash;

I don't observe the crashes in two cases:
1. update a feed manually via the context menu;
2. when using 'Update folder' context menu;

**Comment by lwindolf** [comment] 2015-02-24 22:06
Caused by broken favicons. Fixed in git master with 31402cb. Please retest!

Fix will be released with 1.11.4 and 1.10.14

**Closed by lwindolf** 2015-02-24 22:06 UTC
Labels: bug
