### ISSUE TITLE
Liferea defaults to HTML5 feeds instead of using feed link in page header

### ISSUE THREAD

**Issue by hannobraun** [lwindolf/liferea#1033] opened 2021-10-27 12:18 UTC
I'm currently using Liferea 1.13.6.

Here's what I do:
1. Click "New Subscription..."
2. Paste the address of an HTML page with a `<link>` to an Atom feed
3. Click "OK"

I would expect that this adds a feed based on the Atom feed file that the page links to. However, I found that Liferea defaults to adding an HTML5 feed, instead of using the linked Atom feed. This goes counter to precedence documented in the [announcement blog post](https://lzone.de/liferea/blog/Subscribing-to-HTML5-websites-that-have-no-feed) for this feature.

I wasn't able to find a changelog entry, blog post, or pull request that announced a change to this precedence, so I assume it must be a bug.

Examples from my website, to reproduce the issue:

- https://hanno.braun-odw.eu/about/ - **Works.** Page contains no `<article>`s, Liferea subscribes to the [linked Atom feed](https://hanno.braun-odw.eu/atom.xml).
- https://hanno.braun-odw.eu/updates/ - **Works.** Page contains `<article>`s without any titles. Liferea subscribes to the [linked Atom feed](https://hanno.braun-odw.eu/updates/atom.xml).
- https://hanno.braun-odw.eu/notes/ - **Does not work.** Page contains `<articles>`s with titles and links. Liferea subscribes to those, instead of the [linked Atom feed](https://hanno.braun-odw.eu/notes/atom.xml).
- https://hanno.braun-odw.eu/home/ - **Does not work.** Page contains two lists of `<articles>`s. Liferea subscribes to the ones that contain titles and links, instead of the [linked Atom feed](https://hanno.braun-odw.eu/atom.xml).

It is of course very possible, that I have done something wrong and my `<link>`s are somehow malformed. However, I'm not seeing a problem upon reviewing them, and Liferea still picks them up, if the page has no eligible `<article>`s.

**Comment by lwindolf** [comment] 2022-03-30 22:34
Reproduced.

**Comment by lwindolf** [comment] 2022-03-30 22:36
Root cause is not within the link finding itself (which works see test added with 407fe6d) but seem to be with the detection of wether the URL given for subscription is a HTML document or a feed RSS/XML source. For some reason the RSS/XML link detection is being skipped and the HTML5 feed fallback triggers.

**Comment by lwindolf** [comment] 2022-04-18 20:02
Fixed by explicitly running all HTML-based feed parsers only after actual feed link discovery happens.

**Closed** 2022-04-18 20:01 UTC
Labels: bug

**Comment by hannobraun** [comment] 2022-04-19 10:49
Thank you, @lwindolf!
