### ISSUE TITLE
liferea crashed with SIGSEGV in WebKit::WaylandCompositor::Surface::flushPendingFrameCallbacks 

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#603] opened 2018-02-06 21:23 UTC
The following crash has been reported to Ubuntu's bug tracker:
https://bugs.launchpad.net/ubuntu/+source/liferea/+bug/1747116

```
StacktraceTop:
 WebKit::WaylandCompositor::Surface::flushPendingFrameCallbacks (this=this@entry=0x7fbaab0f3ec8) at ./Source/WebKit/UIProcess/gtk/WaylandCompositor.cpp:258
 WebKit::WaylandCompositor::Surface::setWebPage (this=0x7fbaab0f3ec8, webPage=0x0) at ./Source/WebKit/UIProcess/gtk/WaylandCompositor.cpp:181
 WebKit::AcceleratedBackingStoreWayland::~AcceleratedBackingStoreWayland (this=0x7fbaab0ff2b8, __in_chrg=<optimized out>) at ./Source/WebKit/UIProcess/gtk/AcceleratedBackingStoreWayland.cpp:61
 WebKit::AcceleratedBackingStoreWayland::~AcceleratedBackingStoreWayland (this=0x7fbaab0ff2b8, __in_chrg=<optimized out>) at ./Source/WebKit/UIProcess/gtk/AcceleratedBackingStoreWayland.cpp:62
 std::default_delete<WebKit::AcceleratedBackingStore>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:78
```
Full trace available here: https://launchpadlibrarian.net/355621552/ThreadStacktrace.txt

**Comment by bobkaiser** [comment] 2018-02-23 03:16
I have submitted a similar bug report on bugzilla.redhat.com for Fedora 27 64-bit gnome (wayland mode): https://bugzilla.redhat.com/show_bug.cgi?id=1548256
Segmentation Fault on Start in gnome Wayland
[log_messages.txt](https://github.com/lwindolf/liferea/files/1750354/log_messages.txt)

**Comment by Leiaz** [comment] 2018-02-24 17:55
They are not exactly the same crashes.

@bobkaiser Do other WebKitGtk apps (like the Epiphany browser) work on this machine ? The crash happens inside WebKitGtk after we call `webkit_settings_new ()` so either it is a WebKit bug, or there is something really weird happening.

@paulgevers The crash happens when running dispose on the WebKit widget. It looks like a WebKit bug, and has already been reported [on the WebKit bugzilla](https://bugs.webkit.org/show_bug.cgi?id=183091).

**Comment by bobkaiser** [comment] 2018-02-25 17:53
@Leiaz I ran a test with epiphany and got the same segmentation fault.  Details are in the bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=1548256
Thanks for responding and clarifying the issue.

**Comment by paulgevers** [comment] 2018-02-26 13:45
@Leiaz thanks

**Comment by Leiaz** [comment] 2018-02-27 17:34
Closing this then, as it is either a WebKitGtk bug or a problem with the way the virtual machine handles graphics for Wayland.

**Closed by Leiaz** 2018-02-27 17:34 UTC

**Comment by rich-coe** [comment] 2018-10-29 19:59
I have for a long time been plagued with two types of WebKit crashes.
(1) Displaying some web content (web page) in a tab will crash WebKitWebProcess
(2) Displaying video in liferea after a long ago linux update causes the X server to crash.

I have diagnosed this issue so far to compositing mode in wayland inside WebKit.
I have found a work-around to (2) using the script below as a work-around until I can reproduce the WebKit issue further.  Time will tell if it also affects (1).

```
#!/bin/bash 
export WEBKIT_DISABLE_COMPOSITING_MODE=1
exec /usr/local/bin/liferea -w shown
```

**Comment by lwindolf** [comment] 2018-10-30 21:08
@rich-coe Thank you for the workaround hint!!!
