### ISSUE TITLE
ignores "accels" configuration [regression between 1.12 rc3 and 1.12.3]

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#660] opened 2018-07-21 09:31 UTC
Dear all,

I got a bug report in Debian about Liferea ignoring "accels" configuration: https://bugs.debian.org/903583

Paul

```
Package: liferea
Version: 1.12.3-1
Severity: important

Dear Maintainer,

Liferea ignores my accels configuration file and I am unable to change shortcuts keys.

Thanks.
```
and
```
I can confirm the liferea stable (1.12~rc3) version works fine and detects the accels keys without any problem.
```

**Comment by Leiaz** [comment] 2018-07-21 11:04
That is by design. Despite not being clearly marked as deprecated [GtkAccelMap doesn't work with GAction](https://blogs.gnome.org/chergert/2016/11/14/accelerators-a-history-lesson/). So using `gtk_accel_map_load` doesn't work any more, we would have to parse the file ourselves ...

Custom shortcuts can be set from a python plugin. A very minimal one would look like this : 
```python
from gi.repository import GObject, Peas, Liferea

class CustomShortcutsPlugin (GObject.Object, Liferea.ShellActivatable):
    __gtype_name__ = 'CustomShortcutsPlugin'

    shell = GObject.property(type=Liferea.Shell)

    def do_activate(self):
        self._app = self.shell.get_window().get_application ()
        # Takes a detailed action name and a list of accelerators 
        self._app.set_accels_for_action ("app.search-feeds", ["<Control>j"])
```

**Comment by mozbugbox** [comment] 2018-07-23 14:55
https://github.com/mozbugbox/liferea-plugin-studio/tree/master/accels

**Closed** 2018-07-23 16:39 UTC

**Comment by lwindolf** [comment] 2018-07-23 16:44
I added @mozbugbox solution to the 3rd party plugin list, so you can install the plugin and change the settings.

@mozbugbox: I'd also like to reference your other plugins directly, but so far you haven't ported to Webkit2 yet, I have a cloned repo if you'd like to merge it back!

As for migrating old settings: the new GAction names do not really map to the old accelerator paths. So the migration to 1.12 does break old custom accel settings :-(

**Comment by Leiaz** [comment] 2018-12-26 18:09
`Right` is the correct name, but as explained above the old style accels file doesn't work anymore with GAction.

You can use mozbugbox's plugin to set custom shortcuts.

**Comment by rinaldus** [comment] 2018-12-26 19:48
I installed this plugin, but couldn't find settings where to bind keys.
