### ISSUE TITLE
Scrollbars not always present in the headline area in Liferea 1.12+

### ISSUE THREAD

**Issue by siebenmann** [lwindolf/liferea#549] opened 2017-10-12 18:05 UTC
When I tried out the latest git tip, with the date of items displayed on the right, one of the first things I tried was shrink the amount of space given to the date (by grabbing its divider bar and moving it right). When I moved it far enough right, the scrollbar disappeared entirely, even if I hovered the mouse over the very right side of the window. Widening the date area again sometimes but not always seemed to fix this, and at least once I switched over to my 'Important Items' virtual folder and had the scroll bar not there again, even after I'd made it reappear in the feed where I'd first tried shrinking the date field.
  
(Hopefully this description of what I'm seeing is comprehensible and clear enough.)

**Comment by Leiaz** [comment] 2017-10-13 16:22
Weird. It looks like the whole GtkPaned expands outside the window ...

**Comment by siebenmann** [comment] 2018-05-02 00:09
Is there any possibility of progress on this? Liferea 1.12+ is essentially unusable for me because of this issue combined with the appearing or disappearing column for attachments.

To explain the problem I've run into now: most of my feeds don't have attachments, so they only have the icon/headline/date columns, and I want the headline as wide as possible within my overall window size, leaving minimal space for date. But then when I switch to a feed with attachments (including the 'Important' view), this adds a column for the attachment marker, the Date column is pushed right, and suddenly I don't have scrollbars any more. My options are either to continually adjust the position of the Date column as I move from feed to feed or to permanently see only a relatively small amount of each headline, which makes scanning hard.

(I would be happy to have a date column which clipped the length of the displayed date while preserving the scrollbar.)

**Comment by siebenmann** [comment] 2018-05-02 00:11
I've updated the title of this bug since what was the latest git tip back in last October is now 1.12+.

**Comment by lwindolf** [comment] 2018-05-02 20:32
Hi Chris! Thanks for the update on this. The current source has a serious problem with GtkPane sizings. There are at least two symptoms, the one you describe and #570 / #590. I think they are related. But so far I have no clue what the problem is.

**Comment by Leiaz** [comment] 2018-05-08 17:49
Here is a code sample that reproduce the problem, with a treeview with one resizable column like Liferea : [paned_test.tar.gz](https://github.com/lwindolf/liferea/files/1984996/paned_test.tar.gz) (Github would not let me upload just a .c file ..)

With just one GtkPaned, reproducing the item list + webview part, resizing the treeview column "past" the size of the window makes the window grow in that direction. I think that happens because the scrolled window for the treeview is set to never have an horizontal scrollbar.

With both GtkPaned, the side containing the itemlist + webview is set to shrink : the right side of the item paned disappears outside the window on resize. But setting shrink to false also has annoying effects ...

One way to fix is to let the item list have an horizontal scrollbar, that way the vertical one stays at the window's edge. Or find a mix of resize and shrink settings that works ...

**Comment by Leiaz** [comment] 2018-08-22 16:04
@lwindolf This one could be fixed by changing the item list view to have a horizontal scrollbar. I think this is the best solution as otherwise the feedlist panel or the whole window is resized on column resizing.

(If you like that solution, don't wait for me, I'm not home, I'm on a smartphone for now.)

**Closed** 2018-10-15 20:20 UTC
Labels: bug

**Comment by lwindolf** [comment] 2018-10-15 20:21
I've merged @Leiaz patch to always have the horizontal scrollbar. Will be released with 1.12.6
