### ISSUE TITLE
feed items of search folder not showing as folder child feeds

### ISSUE THREAD

**Issue by patrickjohnson3** [lwindolf/liferea#728] opened 2019-06-01 19:10 UTC
I expected to see the items contained in a search folder displayed as child feeds (when the Test folder is selected). This does not occur. Not sure if this is a bug or I am requesting a feature. I would like to see this behavior work. 

![Screenshot_2019-06-01_15-11-14](https://user-images.githubusercontent.com/49662188/58752587-8cd51a80-847f-11e9-877d-d8b28092c932.png)

The search folder is filtered for Humble Bundle Blog items containing the word Book.

**Comment by Leiaz** [comment] 2019-07-21 16:30
This was disabled on purpose by commit 647f4c6462059a6213358. I can't reproduce the mentioned crash when removing the return, so maybe the bug was fixed by some other change since then, and the feature could be restored. @lwindolf ?

**Comment by lwindolf** [comment] 2023-01-04 21:09
Reverted commit 647f4c6 seems to work now.

**Closed** 2023-01-04 21:09 UTC
