### ISSUE TITLE
Feed names no longer shown in bold font to reflect new items since last read

### ISSUE THREAD

**Issue by pjakma** [lwindolf/liferea#530] opened 2017-08-15 06:17 UTC
Liferea used to highlight in bold those feeds which have been updated with new items, since an item was last read in that feed. This was very useful to scan over the feed list and spot the ones updated since last read.
This behaviour seems to have gone in 1.12-rc3 (Fedora 26 package), sadly. If it could be restored, that would be great.

**Comment by yaneti** [comment] 2017-08-18 12:07
Pull request #532 is another attempt and bringing back the boldnes, with a plugin

**Comment by pjakma** [comment] 2017-08-18 21:32
Awesome :)

Just one thing, that plugin seems to set bold if there are any unread. The previous behaviour I think was that bold was cleared if I went to a folder and read any unread item (even if unread were still left), and bold was enabled again if the feed was refresh.

I.e., I want the bold to tell me if there are new items since I last read in that folder, not if there unread items, as used to be the case. Make sense? It's very useful!

**Comment by yaneti** [comment] 2017-08-18 22:15
Sounds potentially useful, although it would be probably more involved that the current simplistic plugin approach. 

But perhaps you are missremebering how 1.10 worked?
I just tried 1.10.19 and bold seems to be cleared only when there are no unread items.

**Comment by pjakma** [comment] 2017-08-19 14:18
Hmm, maybe I am mis-remembering. I /thought/ it was the way I described it, but if you say it wasn't, then.. :) Using the plugin, and that's definitely an improvement, thanks!

**Comment by nekohayo** [comment] 2017-08-26 21:55
This was on purpose (the rationale is explained in my comments in issue #29)

**Comment by lwindolf** [comment] 2017-09-07 13:19
Closing this because I believe the added plugin solves the actual regression. The regression the title suggests is not correct. 1.10 behaviour was all feeds with unread items to have bold titles. The plugin restores that behaviour.

**Closed by lwindolf** 2017-09-07 13:19 UTC
Labels: plugin
