### ISSUE TITLE
liferea doesn't show the reading split pane

### ISSUE THREAD

**Issue by shalom938** [lwindolf/liferea#1237] opened 2023-04-11 15:06 UTC
liferea doesn't show the reading pane. its actually an issue i know for few years already. its discussed here in arch community
https://bbs.archlinux.org/viewtopic.php?id=263954
in the past when i used debian i could draw it up from the bottom. but now on opensuse i can't do it. 
if i squeeze the window it shows up, when enlarging or maximizing the window again it disappears. 
[Screencast from 2023-04-11 18-04-41.webm](https://user-images.githubusercontent.com/170266/231206017-9bccccd8-eda7-461d-b2b7-2f4853106d11.webm)

**Comment by lwindolf** [comment] 2023-04-11 21:16
@shalom938 With which version are you seeing this effect?

**Comment by shalom938** [comment] 2023-04-13 17:25
@lwindolf  version 1.14.4, opensuse tumbleweed

**Comment by AlexZeitler** [comment] 2023-04-20 09:22
Same issue (and described full screen behavior) here with 1.14.5 on Xubuntu 22.04

**Comment by lwindolf** [comment] 2023-04-22 09:17
@shalom938 @AlexZeitler Could you please provide a screenshot?

**Comment by shalom938** [comment] 2023-04-23 07:02
@lwindolf I provided screen-cast in the first message

**Comment by AlexZeitler** [comment] 2023-04-24 05:09
Fullscreen:

![image](https://user-images.githubusercontent.com/287480/233904743-7cb2e531-e3fb-4324-98f4-19bec840dfef.png)

Windowed:

![image](https://user-images.githubusercontent.com/287480/233904916-143e689d-2065-4693-91fa-6bc5edb69df7.png)

**Comment by lwindolf** [comment] 2023-04-24 20:39
@shalom938 @AlexZeitler Thanks for providing screenshots/casts. I cannot reproduce the effect, but got a hint from @nekohayo that this might be Wayland related. Are you on Wayland? If yes, would you have the possibility to test with an Xorg session (yoiu can usually do switch this in the session manager upon login)?

**Comment by AlexZeitler** [comment] 2023-04-24 23:23
I'm on Xubuntu 22.04 with xfce 4.16 which doesn't have Wayland support AFAIK.

**Comment by nekohayo** [comment] 2023-04-25 00:09
It seems to me that OP (Shalom938) is indeed using the Wayland version of GNOME Shell, it's "too smooth / too frame-perfect" when the window resizes in the video ;) I guess it'll be interesting to know if they can reproduce the bug in the Xorg GNOME session too.

I'm guessing this might turn out to be some sort of race condition after all, and whether one is running Wayland or not makes the performance profile behave differently so the issue may manifest in one session and not the other, on one graphics card driver and not the other, etc., where you then randomly get things like #534 and #901...

**Comment by shalom938** [comment] 2023-04-27 18:00
@lwindolf @nekohayo , Yes , I am on wayland. opensuse. 
 I started the computer with Xorg session and its the same issue. see attached screencast.

[Screencast from 2023-04-27 20-59-30.webm](https://user-images.githubusercontent.com/170266/234952117-a5245bed-31d6-40e7-a082-c8d58b8ca6f4.webm)

**Comment by lwindolf** [comment] 2023-06-27 20:07
Argh I found a nasty logic bug in the implementation that was intended to fix the issues. The broken fix probably made it worse: https://github.com/lwindolf/liferea/commit/3782fef1be2311fd89ffb1a8df320566b4496d4c

Everyone please retest with master and give feedback!

**Comment by lwindolf** [comment] 2023-09-15 21:26
Closing this a I believe it is fixed. Please open a new issue if you still experience the problem.

**Closed by lwindolf** 2023-09-15 21:26 UTC
Labels: bug
