### ISSUE TITLE
Blog post truncated after a YouTube embed

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#955] opened 2021-01-17 17:39 UTC
I don't know why, https://fortintam.com/blog/video-on-the-origins-of-the-flow-game/ shows up truncated in Liferea, just after the video (which, surprisingly, does show in Liferea!); there are no errors reported by Liferea's GUI (ignore the fact that my pane is vertical in this screenshot, I just changed the orientation using the GTK Inspector :) :

![Screenshot from 2021-01-17 12-29-35 crop](https://user-images.githubusercontent.com/479401/104850971-2012cc00-58c0-11eb-9a0a-d09323c7a7a1.png)

(there is no scrolling content beyond that point, it's just empty)

The W3C feed validator says my feed is valid (sure, it makes some "recommendations" about a few things here and there, but it still says the feed is valid):

![Screenshot from 2021-01-17 11-56-20](https://user-images.githubusercontent.com/479401/104851118-02923200-58c1-11eb-922f-d058b0a3d3f4.png)

...and [Planet GStreamer](https://gstreamer.freedesktop.org/planet/) (an aggregator running PlanetPlanet) has no trouble showing the contents beyond the point where the video is embedded:

![Screenshot from 2021-01-17 11-55-58 crop](https://user-images.githubusercontent.com/479401/104851056-98798d00-58c0-11eb-8658-d1397ec8f3db.png)

**Comment by rich-coe** [comment] 2021-05-31 02:53
I think the root cause of this is the use of 'self closing tag' (valid in xml)
in items and it's not displaying in webkit because it's not valid html-5.
See #992.

**Comment by rich-coe** [comment] 2021-06-01 13:04
I've created a PR to fix this issue.

**Comment by lwindolf** [comment] 2021-06-18 21:26
PR #996 was merged.

**Closed** 2021-12-06 21:12 UTC
Labels: bug
