### ISSUE TITLE
Feed > Properties fails to load liferea.ui, causes SIGTRAP

### ISSUE THREAD

**Issue by g4jc** [lwindolf/liferea#273] opened 2015-10-18 14:44 UTC
When selecting a feed, right clicking, and choosing "properties" the ui usually crashes with the following information from the terminal:

** (liferea:9573): ERROR **: Loading /usr/share/liferea/liferea.ui failed.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00000385db38064b in g_logv () from /usr/lib/libglib-2.0.so.0

dmesg:
[ 5489.283755] traps: liferea[22839] trap int3 ip:35c01ac064b sp:3db909a4170 error:0
[ 5534.732060] traps: liferea[7838] trap int3 ip:3bc0a18664b sp:3da183debd0 error:0

Liferea Version: 1.10.16
Glib version: glib-1.2.10-12 (Arch package)

**Comment by slawqo** [comment] 2015-10-18 16:59
I have exactly same issue. Same liferea version on Arch linux too :/

**Comment by fstirlitz** [comment] 2015-10-25 09:20
Looks like a duplicate of #258. (Which I have just debugged myself.)

**Comment by lwindolf** [comment] 2015-10-30 23:08
I believe this to be fixed. Please retest with recent releases!

**Closed by lwindolf** 2015-10-30 23:08 UTC
Labels: bug
