### ISSUE TITLE
Tiny Tiny RSS source only fetches the "Fresh artlcles" list and not the "All articles" list even if the latter has unread articles

### ISSUE THREAD

**Issue by lgp171188** [lwindolf/liferea#1065] opened 2021-12-27 15:28 UTC
I am seeing this issue on Liferea 1.13.4 on Kubuntu 21.10 amd64 and a very recent revision of Tiny Tiny RSS. Even when there are some unread articles in the `All articles` list that are not in the `Fresh articles` list, Liferea doesn't show them at all.

**Comment by lwindolf** [comment] 2022-09-29 20:47
Hmm... API wise Liferea is fetching the `All articles` target. But we apply a limit (the global feed cache limit). This means no items beyond a certain number of items is fetched. So it could be that your limit is 1000 and the 1001st item of a feed is unread. In this case Liferea will never pull it.

Due to a missing TTRSS test instance I cannot currently test this...

Could you test the following scenario:
1. Update your ttrss subscription in Liferea
2. In one of the ttrss feeds mark everything read
3. In TinyTinyRSS itself mark a recent item in the feed as unread
4. Pull again in Liferea

This way the item should not be fresh anymore but still be matched by the `All articles` target.

**Comment by lgp171188** [comment] 2022-10-21 15:25
@lwindolf, sorry for the very late reply. I do not use Tiny Tiny RSS any more and hence do not have a setup where I can test this. Sorry!

**Comment by lwindolf** [comment] 2022-10-22 21:41
@lgp171188 Ok. Closing this as not reproducible.

**Closed by lwindolf** 2022-10-22 21:42 UTC
