### ISSUE TITLE
Unable to use a different browser

### ISSUE THREAD

**Issue by stefanos82** [lwindolf/liferea#536] opened 2017-08-28 02:12 UTC
Specs
--------
OS: GNU / Debian testing 64-bit, 4.12.0-1-amd64
Liferea version: 1.12~rc3-1

Issue
------

I'm trying to use a different browser in place of `Default Browser` and after I restart it, it restores the previous one I have manually set.

For instance, I want to use `waterfox` in place of `firefox-esr`, but it won't let me do so, not even when I add it with full path.

Any feedback?

Cheers.

**Comment by lwindolf** [comment] 2017-09-03 16:30
I cannot reproduce the issue with git master. Can you please run from a terminal and lookup for any DConf related exception when you change the settings?

**Comment by stefanos82** [comment] 2017-09-03 17:42
I have run it from terminal and edited my browser settings to use `waterfox` and these are the results (before and after the changes):

### BEFORE

```bash
stefanos@debian:~$ liferea
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 37, in do_activate
    raise ValueError("Failed to unlock GnomeKeyring, error "+result)
TypeError: Can't convert 'Result' object to str implicitly

(liferea:1261): Gtk-WARNING **: Allocating size to GtkWindow 0x557ef0520280 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(liferea:1261): Gtk-WARNING **: Allocating size to GtkWindow 0x557ef0520280 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

```bash
stefanos@debian:~$ liferea --debug-conf
CONF   : proxy is disabled by user
CONF   : Manual proxy settings are now NULL:0 NULL:NULL
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 37, in do_activate
    raise ValueError("Failed to unlock GnomeKeyring, error "+result)
TypeError: Can't convert 'Result' object to str implicitly
CONF   : Scheduling feedlist save
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0

(liferea:9119): Gtk-WARNING **: Allocating size to GtkWindow 0x55b0a1594280 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
CONF   : Setting startup-feed-action to 0
CONF   : Setting maxitemcount to 1000
CONF   : Setting default-update-interval to 1440
CONF   : Setting folder-display-mode to 1
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-vpane-pos to 238
CONF   : Setting last-hpane-pos to 373
CONF   : Setting last-wpane-pos to 100
CONF   : Forced feed list save
CONF   : Setting last-zoomlevel to 112
```
AFTER
----------

```bash
stefanos@debian:~$ liferea
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 37, in do_activate
    raise ValueError("Failed to unlock GnomeKeyring, error "+result)
TypeError: Can't convert 'Result' object to str implicitly

(liferea:2604): Gtk-WARNING **: Allocating size to GtkWindow 0x563ce6b9e280 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

```bash
stefanos@debian:~$ liferea --debug-conf
CONF   : proxy is disabled by user
CONF   : Manual proxy settings are now NULL:0 NULL:NULL
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 37, in do_activate
    raise ValueError("Failed to unlock GnomeKeyring, error "+result)
TypeError: Can't convert 'Result' object to str implicitly
CONF   : Scheduling feedlist save
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0

(liferea:10188): Gtk-WARNING **: Allocating size to GtkWindow 0x561a5f8b2280 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
CONF   : Setting startup-feed-action to 0
CONF   : Setting maxitemcount to 1000
CONF   : Setting default-update-interval to 1440
CONF   : Setting folder-display-mode to 1
CONF   : Setting last-window-state to 0
CONF   : Setting last-window-state to 0
CONF   : Setting last-vpane-pos to 238
CONF   : Setting last-hpane-pos to 373
CONF   : Setting last-wpane-pos to 100
CONF   : Forced feed list save
CONF   : Setting last-zoomlevel to 112
```

Is there anything else that I could try to provide more feedback?

**Comment by baermb** [comment] 2017-11-16 17:35
FWIW, I'm seeing the same issue (Fedora 26, liferea 1.12-rc3).  Changing the manual browser string doesn't get saved.  It does show up as changed in the preference dialog until the next startup of liferea.  But it still uses the old string regardless.

I use a simple, ugly work around for it.  It may work for you.  Create a script to open your browser of choice with the same name as the executable that can't be changed in the preference dialog. Then place it higher in the executable path than the actual executable.

**Comment by Leiaz** [comment] 2017-11-19 15:55
@stefanos82 Are you sure you were using git master ? This should be fixed by #511.

**Comment by stefanos82** [comment] 2017-11-19 16:55
@Leiaz I never said anything about using `git master`.

I just reported the issue with version `1.12~rc3-1` that is available on my Debian testing 64-bit system.

**Comment by Leiaz** [comment] 2017-11-19 17:23
Ah sorry, I misread and thought @lwindolf asked you to try git master.

**Comment by lwindolf** [comment] 2017-11-20 20:42
@stefanos82 A friendly reminder, that it is a common OSS rule to always test using the upstream version when reporting upstream. If you want to report for your distro version always report a bug at the distro. Otherwise you make maintainers life really hard and cause extra triage work.

**Comment by da2x** [comment] 2017-12-31 13:34
This issue can probably be closed then.

**Comment by Leiaz** [comment] 2018-01-17 11:50
Closing this, as it is fixed in current release.

**Closed by Leiaz** 2018-01-17 11:50 UTC
Labels: bug
