### ISSUE TITLE
Privacy issue while using TinyTinyRSS in Liferea (and maybe all other external sources)

### ISSUE THREAD

**Issue by Perflyst** [lwindolf/liferea#678] opened 2018-10-13 17:54 UTC
I connected TinyTinyRSS  in Liferea.
Since I wanted to see the tt-rss useragent I setup an own rss feed. I added it via the webclient from tt-rss and then updated liferea.

I have seen a tt-rss useragent in access log and also the liferea useragent. Both have accessed the feed.

Why does liferea even connects to the feed? It is enough to connect to the tt-rss instance and pull the feeds from there, isn't it?

I check this via the tt-rss mobile app. The app does not connect to the feeds itself it just connects to the tt-rss instance and pulls the feeds.

**Comment by Leiaz** [comment] 2018-10-15 20:59
@lwindolf I think the problem is that Liferea connects to the server serving the feed, instead of only connecting to the tt-rss instance. Maybe for the favicon ?

**Comment by Perflyst** [comment] 2018-10-16 10:31
@Leiaz is correct. All my feeds dont need any auth and are public on the internet.
Liferea connects to them and I dont know why because tt-rss should fetch them on the server and liferea should just crawl them from tt-rss.
Maybe it is because of the favicon but tt-rss also pulls the favicon. If it is really the favicon please give users an opt-in or opt-out for this.

**Comment by lwindolf** [comment] 2018-10-16 19:00
The favicon pulling makes sense. It should be done without auth per-default (so no opt-out is necessary at all).

@Perflyst Can you please still post some example URLs from your log so the code paths can be verified correctly?

**Comment by Perflyst** [comment] 2018-10-17 17:00
I added http://rss.perflyst.de/feed.xml via tt-rss and than opened liferea. I do not have any other feeds or sources in liferea, only tt-rss as a source.

access log from the server (p.s. dont care about ip, it is just a tor exit)
```
185.220.101.22 - - [17/Oct/2018:18:56:52 +0200] "GET /feed.xml HTTP/1.1" 200 833 "-" "Liferea/1.12.5a (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
185.220.101.22 - - [17/Oct/2018:18:56:53 +0200] "GET / HTTP/1.1" 200 653 "-" "Liferea/1.12.5a (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
185.220.101.22 - - [17/Oct/2018:18:56:54 +0200] "GET /favicon.ico HTTP/1.1" 404 409 "-" "Liferea/1.12.5a (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
185.220.101.22 - - [17/Oct/2018:18:56:54 +0200] "GET /favicon.ico HTTP/1.1" 404 409 "-" "Liferea/1.12.5a (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
185.220.101.22 - - [17/Oct/2018:18:56:55 +0200] "GET /favicon.ico HTTP/1.1" 404 409 "-" "Liferea/1.12.5a (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
```

**Comment by Perflyst** [comment] 2018-10-19 16:45
@lwindolf is that what you wanted? Can I help you in any other way?

**Comment by lwindolf** [comment] 2018-10-22 16:11
@Perflyst Yes, exactly this. I just need to find time for debugging this :-(

**Comment by Perflyst** [comment] 2018-11-09 19:50
One question: Can I disable the connection to the feeds completely? I do not even need the favicon.

**Comment by gsantner** [comment] 2019-01-05 02:03
Noticed this too and for me this is a big privacy issue. I explicitly host tt-rss on a external host to NOT let all 100 feed's servers at same time know my personal device current IP (and thus tracking).

**Comment by poetsmeniet** [comment] 2019-01-10 13:57
@lwindolf is anyone working on this? I could pick it up

**Comment by lwindolf** [comment] 2019-01-10 14:00
@poetsmeniet  Nope. I want to address this, but don't have time. Would be great if you could work on it!!!

**Comment by poetsmeniet** [comment] 2019-01-15 08:04
@lwindolf cool! I will have a look and see if I can come up with some solutions..

**Comment by poetsmeniet** [comment] 2019-01-26 11:40
Hi guys :)

I managed to put a little time into this issue and am now able to reproduce the issue.. need to find more time though to dig into the code.

**Comment by poetsmeniet** [comment] 2019-01-29 07:18
I am trying to reproduce the privacy issue. I have set up ttrss on server 1, server 2 is hosting feeds. I added these feeds to ttrss and then added the ttrss feed to Liferea.

On updating, the favicon procedure is called, there are 6 different methods that are possible, and visible in the server 1 access log (but not in server 2). 

Note: only the first method could possibly be a privacy issue, as it would parse the icon element in the feed. If this icon element pointed externally.. The latest rolling release of ttrss does not publish said icon element.

So..
My Liferea instance's favicon is updated with the logo of ttrss, not of the feed itself. I can't seem to reproduce the privacy issue.

@Perflyst: can you get me the feed you used? That might help in finding the issue

**Comment by Perflyst** [comment] 2019-01-29 17:39
I bumped it up again: https://rss.perflyst.de/feed.xml
TinyTinyRSS is on latest master, Liferea is 1.12.6 from GitHub compiled.
```
# add feed via tt-rss web front end
XX1 - - [29/Jan/2019:18:36:14 +0100] "GET /feed.xml HTTP/1.1" 200 777 "-" "Tiny Tiny RSS/18.12 (c7c9c5f) (http://tt-rss.org/)"
XX1 - - [29/Jan/2019:18:36:14 +0100] "GET /feed.xml HTTP/1.1" 200 777 "-" "Tiny Tiny RSS/18.12 (c7c9c5f) (http://tt-rss.org/)"
# open liferea and refresh
XX - - [29/Jan/2019:18:36:45 +0100] "GET /feed.xml HTTP/1.1" 200 833 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [29/Jan/2019:18:36:47 +0100] "GET / HTTP/1.1" 200 654 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [29/Jan/2019:18:36:48 +0100] "GET /favicon.ico HTTP/1.1" 404 410 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [29/Jan/2019:18:36:49 +0100] "GET /favicon.ico HTTP/1.1" 404 410 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [29/Jan/2019:18:36:51 +0100] "GET /favicon.ico HTTP/1.1" 404 410 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
```

**Comment by Perflyst** [comment] 2019-01-30 20:06
I kept the log file enabled and it seems like Liferea only does these connections on the inital startup of Liferea and not on the next pulls from tt-rss. It is always the same requests

```
XX - - [30/Jan/2019:19:43:53 +0100] "GET /feed.xml HTTP/1.1" 200 833 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [30/Jan/2019:19:43:54 +0100] "GET / HTTP/1.1" 200 704 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [30/Jan/2019:19:43:56 +0100] "GET /favicon.ico HTTP/1.1" 404 410 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [30/Jan/2019:19:43:58 +0100] "GET /favicon.ico HTTP/1.1" 404 410 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
XX - - [30/Jan/2019:19:43:59 +0100] "GET /favicon.ico HTTP/1.1" 404 410 "-" "Liferea/1.12.6 (Linux; https://lzone.de/liferea/) AppleWebKit (KHTML, like Gecko)"
```

**Comment by poetsmeniet** [comment] 2019-02-08 09:25
@Perflyst I am afraid I can't reproduce this issue. My setup works just as it should. I also see the favicon requests in the logs, but **not on the feed server** but **on the ttrss server**.. so that is fine. Also I don't see liferea getting the feed.xml file..

If you export your feed list in liferea, how many items do you have there? These items should only point to your ttrss server, something like: https://www.yourttrssfeedserver.com/tinytiny/public.php?op=rss&id=18&key=r3wix75c4d3bhcc5cec

**Comment by Perflyst** [comment] 2019-02-08 10:49
Uhm, if I export via "Subscriptions" -> "Export Feed List" I get
```xml
<?xml version="1.0"?>
<opml version="1.0">
  <head>
    <title>Liferea Feed List Export</title>
  </head>
  <body/>
</opml>
```

**Comment by poetsmeniet** [comment] 2019-02-08 11:09
That is unexpected.. :-P you have feed items coming in though?

**Comment by poetsmeniet** [comment] 2019-02-08 11:25
@Perflyst Can you check out your ~/.local/share/liferea/liferea.db? It is a sqlite file, look for any references to feed.xml there..

**Comment by Perflyst** [comment] 2019-02-08 11:50
```bash
$ cat liferea.db | grep feed.xml
Binary file (standard input) matches
```
It is listed there, yes. There are also all other feeds I have subscribed via tt-rss.

**Comment by Perflyst** [comment] 2019-02-10 14:34
I tested this in a new virtual machine, with latest liferea release from github. Same behaviour.
Also started with `--debug-trace` just shows `feedlist_auto_update`, `favicon_download_run` and `itemlist_merge_itemset`, so nothing special.

**Comment by poetsmeniet** [comment] 2019-02-14 14:21
Ok dude, let me contact you on xmpp for the details.. don't know when I will have the time, but I will be in touch

**Comment by lwindolf** [comment] 2022-10-18 20:33
I decided to prevent the possibility entirely in the code. With fd0afaf8 favicons are always fetched **without** credentials. This might break a few border use cases where an authenticated feeds website does not provide its own favicon without basic auth, but this usually should not be the case as there is always a login page which has the favicon without auth.

So better safe then sorry. With this I consider the issue dealt with.

**Closed by lwindolf** 2022-10-18 20:33 UTC
Labels: bug
