### ISSUE TITLE
New Subscription shown on start up

### ISSUE THREAD

**Issue by AndyM48** [lwindolf/liferea#1359] opened 2024-05-09 06:20 UTC
Whenever I start liferea I have a feed "New Subscription" shown which  have to delete.

I have checked and it is not shown in feedlist.opml

**Comment by lwindolf** [comment] 2024-05-10 14:40
Which start command do you use to start Liferea? Because we have a helper script "liferea-add-feed" which will launch Liferea with a new subscription. It sounds like you maybe using it.

**Comment by AndyM48** [comment] 2024-05-11 05:49
I added your .desktop file to my autostart folder so the start command is `Exec=liferea %U`

**Comment by lwindolf** [comment] 2024-05-12 21:01
Sounds harmless

**Comment by AndyM48** [comment] 2024-05-13 05:33
It is a nuisance having to delete it every time liferea starts!

**Comment by AndyM48** [comment] 2024-05-13 05:38
and each time it starts it adds another "New Subscription" if it is not deleted.

Starting without the %U or "%U" removes the problem.

**Comment by nekohayo** [comment] 2024-06-29 00:43
It's a bit unclear whether you created your own custom launcher to begin with, or if you are using the standard one provided by the package and desktop environment.

Overall this ticket here is not a bug report, I would recommend closing it now.

**Comment by AndyM48** [comment] 2024-06-29 05:44
No, as I said, I used your .desktop file to launch liferea on startup. I will check to see if there is still a problem.

Yes, same problem, `liferea %U` adds a `New Subscription` every time.

Artix (Arch) Linux 6.9.6
Openbox 3.6.1-10
Liferea 1.14.6

**Comment by AndyM48** [comment] 2024-06-29 05:57
It seems that the standard launcher can accept a URL and add it if present. If no URL is present then "New Subscription" is used instead. This is without a `-a` flag.

If this is not the intention then what is the reason for adding the `%U` to the launcher exec command?

**Comment by lwindolf** [comment] 2024-06-29 09:54
@AndyM48 The .desktop file defining the %U is to serve to use cases

- direct click e.g. GNOME/KDE panel or some type of launcher (here %U should expand to "")
- "Open With..." for example via file mananger of by MIME type association e.g. in a browser (here %U should expand to a filename or URL)

Both use case call Liferea with the desktop file and need to be supported. When I start with

    liferea ""

the current code creates a new subscription. I think this might be what is happening in your case. Why this only happens for you I cannot tell.

I'll add a check for empty strings to the code to solve this.

**Comment by AndyM48** [comment] 2024-06-29 10:15
Understood.
>Why this only happens for you I cannot tell.
Nor me

Please note in my previous comment, if %U is an existing subscription, liferea will ADD the %U as a new subscription, so checking for an empty string would only be a partial answer, you would also have to check for a duplicate of an existing subscription, and if true, open with the focus on the existing subscription instead of re-adding it.

**Comment by lwindolf** [comment] 2024-06-29 18:57
Both issues (empty URL, duplicate check) should be addressed. Will be released in 1.15.8

**Closed** 2024-06-29 18:56 UTC
