### ISSUE TITLE
Extended image format support for Reading Mode

### ISSUE THREAD

**Issue by Saijin-Naib** [lwindolf/liferea#1126] opened 2022-07-09 10:45 UTC
Right now it seems that sites that host upcoming image formats like webp/avif/heic/heif load placeholder images that can't be viewed in reader mode, though exiting reader mode allows the internal browser to fully-display the content. Are these formats maybe not in the list of filetypes considered "article content"?

Reader Mode for Phoronix:  
![image](https://user-images.githubusercontent.com/19295950/178102360-c12b43e8-04c0-4dd7-9875-0ab64f043aed.png)

Internal Web-Browser for Phoronix:  
![image](https://user-images.githubusercontent.com/19295950/178102378-4f90052b-bbd3-45fa-be8a-db6f1031f50b.png)

Liferea View Image:  
![image](https://user-images.githubusercontent.com/19295950/178102408-07464d5a-6473-4a0d-ab12-ad0e865d8852.png)

**Comment by lwindolf** [comment] 2022-07-23 15:30
This was actually a base URL problem. You see this in your 3rd screenshot where the image path is broken.

I cannot reproduce this anymore with master. Please retest!

**Comment by Saijin-Naib** [comment] 2022-07-23 16:43
Sorry for the mis-report. I'll retest if I can get it to compile for my distro (or if this fix is in a new tag)

**Comment by Saijin-Naib** [comment] 2022-07-28 01:47
I'm finding that with v1.13.9 and (I guess the base url changes/fixes), that most every article source that used to render mostly correctly, fail to render at all and instead load the full page in the internal Liferea Browser.

Phoronix, as used above, behaves this way now:  
![image](https://user-images.githubusercontent.com/19295950/181402416-72600c0c-fec9-4478-b246-4c1b6bf586ff.png)

The error message:  Reader Mode Not Possible. Loading URL unfiltered...
![image](https://user-images.githubusercontent.com/19295950/181402531-e8077c13-a52b-412b-a907-dfe65c4681df.png)

**Comment by lwindolf** [comment] 2022-07-28 19:10
@Saijin-Naib That's strange. I cannot reproduce this regression (tested with Phoronix and the same article you selected).

There was an Readability.js upgrade included in 1.13.9 though...

**Comment by lwindolf** [comment] 2022-07-28 19:12
Reopening the issue because there are still non-rendering images (due to missing base URI) when used with Phoronix. In this case no base URI is set at all anywhere in the rendering output.

This needs fixing.

**Comment by Saijin-Naib** [comment] 2022-07-28 19:53
> @Saijin-Naib That's strange. I cannot reproduce this regression (tested with Phoronix and the same article you selected).
> 
> There was an Readability.js upgrade included in 1.13.9 though...

Would my settings for each source impact this? It seems random as some articles in a troublesome feed will work seemingly at random, same for feeds that normally work having failed article loads as well.

Anything I can provide for you to test/reproduce?

**Comment by lwindolf** [comment] 2022-09-21 17:28
@Saijin-Naib Sorry, about taking so long to work on it. No, there is nothing on your side to workaround. It needs to be fixed in the code.

**Comment by Saijin-Naib** [comment] 2022-09-21 17:51
No worries! I appreciate you taking a look at it.

**Comment by lwindolf** [comment] 2022-09-23 22:28
Should be solved now.

**Closed** 2022-09-23 22:28 UTC
