### ISSUE TITLE
Normal view pane size is borked when using Liferea maximized

### ISSUE THREAD

**Issue by theychx** [lwindolf/liferea#570] opened 2017-12-13 11:37 UTC
In https://github.com/lwindolf/liferea/pull/546 you made an otherwise sane change to Liferea, so that all panes resize with the main window. This unfortunately has the side effect of borking pane size in maximized state. I always use Liferea maximized, and now when I start Liferea the bottom pane is always very small, sometimes almost invisible. Re-adjusting pane size and restarting does not help.

As expected, reverting https://github.com/lwindolf/liferea/pull/546/commits/25db4aa60d87b04cedeaf6bb5502b1cced96b9ea solves this problem.

**Comment by heynnema** [comment] 2017-12-16 02:28
Same problem. Maximized, I always have to manually readjust the pane size after starting Liferea.

**Comment by lwindolf** [comment] 2017-12-17 23:48
@Leiaz Could you have a look at this behaviour?

**Comment by Leiaz** [comment] 2017-12-18 19:14
I can reproduce in a VM with Gnome. It could have to do with the way the GtkPaned position is saved and restored.

As a workaround you can try to Unmaximize Liferea, resize the window to almost maximized size, quit Liferea, and start it again. With my Fedora VM, despite the `last-window-maximized` setting being false after quitting Liferea, it will be maximized when restarting, probably due to gnomish magic ... And it looks like the pane doesn't shrink (too much) any more when quitting and restarting after that.

**Comment by heynnema** [comment] 2017-12-18 19:56
@Leiaz your workaround doesn't work. Liferea doesn't remember its window size/position either.

**Comment by Leiaz** [comment] 2017-12-19 20:29
@heynnema  If you were quitting by closing the window, you can try to quit by the menu. Liferea may sometimes try to save the window size when it is already getting destroyed.

Is everyone using Gnome or does this happen with other window managers ?

Even if I remove the window save/restore size code, and directly bind the GtkPaned `position` property to Liferea corresponding GSettings key, it only works when the window isn't maximized.

When the window is maximized, when the GtkPaned position is set to the previous value, it takes that value, and then the value changes automatically, multiple times, to something bigger that pushes the separator down.

If I connect to the position setting changes I see : 
>  set POS : 209
HPANE POS in callback : 238
HPANE POS in callback : 179
HPANE POS in callback : 208
HPANE POS in callback : 438
HPANE POS in callback : 409

I'll try writing a separate example to test if this is due to something Liferea does or a Gtk bug ...

**Comment by theychx** [comment] 2017-12-19 21:04
> Is everyone using Gnome or does this happen with other window managers ?

I use Gnome. Just tested Liferea with Openbox, where it exibits the same behaviour.

**Comment by theychx** [comment] 2017-12-19 21:52
>  With my Fedora VM, despite the last-window-maximized setting being false after quitting Liferea, it will be maximized when restarting, probably due to gnomish magic ... And it looks like the pane doesn't shrink (too much) any more when quitting and restarting after that.

On my Debian Sid box the behaviour is the same. Still, the bottom pane shrinks a bit after each restart.

**Comment by Leiaz** [comment] 2017-12-20 15:16
Thanks for testing !
So ... It looks like it was already reported [as a GTK bug](https://bugzilla.gnome.org/show_bug.cgi?id=733638) in 2014.

I'll try to write a workaround.

**Comment by Leiaz** [comment] 2017-12-21 20:36
In #573 I disable resize when the window starts maximized, and it looks like it works. But in wide view, even when the window isn't maximized, the separator still moves a bit from its restored position ...

**Comment by theychx** [comment] 2017-12-21 21:54
@Leiaz Works great with normal view (both maximized and normal window). Thanks!

**Comment by lwindolf** [comment] 2017-12-26 23:18
Patch #573 was merged.

**Closed by lwindolf** 2017-12-26 23:18 UTC
Labels: bug

**Comment by heynnema** [comment] 2017-12-31 16:28
1.12.1 is an improvement, but it still doesn't fully remember the exact placement of the pane separator across restarts.
