### ISSUE TITLE
How about a Flatpak version on FlatHub ?

### ISSUE THREAD

**Issue by antistress** [lwindolf/liferea#804] opened 2020-03-28 02:06 UTC
Hi,
I see that 1.12.5 version says "Added flatpak JSON"
I'd love to get a flatpak version of Liferea
Are there any plans to have Liferea on FlatHub ?
https://github.com/flathub/flathub/wiki/App-Submission

Thanks for Liferea, great piece of software :)

**Comment by grdryn** [comment] 2020-04-11 22:50
+1, I came here to find out the same thing. :slightly_smiling_face: 

Nice that there's at least a manifest...I'll try that locally for now, but having it available from a registry such as flathub would be awesome. 

> Thanks for Liferea, great piece of software :)

Also this :point_up:

**Comment by lwindolf** [comment] 2020-04-15 18:56
I sadly do not have enough time for Liferea right now. Flatpack would just be another maintenance task that is missing time :-(

Would be great if someone could maintain such a package. The existing flatpack descriptor was contributed a while ago.

**Comment by mikelolasagasti** [comment] 2020-10-04 18:39
https://github.com/flathub/flathub/pull/1872

A couple of simple patches are needed, will submit them later. I tested with a build from master and is working fine for me. Build can be installed with:

    $ flatpak install --user https://dl.flathub.org/build-repo/28220/net.sourceforge.liferea.flatpakref

**Comment by mikelolasagasti** [comment] 2020-10-05 07:46
Flatpak has been published in Flathub:

https://flathub.org/apps/details/net.sourceforge.liferea

**Comment by mikelolasagasti** [comment] 2020-10-09 22:34
@lwindolf I think this issue can be closed as Liferea is available at FlatHub now

**Closed** 2020-10-10 10:19 UTC

**Comment by antistress** [comment] 2020-10-11 06:34
Hi,
Thank you so much for it !
I took the time to install it and to do some tests
Here's the bug I found : #897

**Comment by nekohayo** [comment] 2020-10-30 14:42
Hi @mikelolasagasti ; just a theoretical nitpick... is using net.sourceforge.liferea the right namespace to use considering it's no longer been on Sourceforge (thankfully) for years? Maybe com.github etc. would be better, or de.lzone (reflecting the fact that the website itself is https://lzone.de/liferea/ )?

Speaking of website, once the question above is decided, @lwindolf would you like to advertise the Flathub Flatpak into https://lzone.de/liferea/install.htm next to the Snap package?

**Comment by mikelolasagasti** [comment] 2020-10-30 15:30
> Hi @mikelolasagasti ; just a theoretical nitpick... is using net.sourceforge.liferea the right namespace to use considering it's no longer been on Sourceforge (thankfully) for years? Maybe com.github etc. would be better, or de.lzone (reflecting the fact that the website itself is https://lzone.de/liferea/ )?

I followed the naming of AppData, GSettings or Desktop file. It can be changed of course and I can create a PR for that, but would require @lwindolf to accept it. So, Lars, what's your opinion on this?

**Comment by lwindolf** [comment] 2021-01-10 18:32
@nekohayo Flatpak install instructions added on website.

I also dislike the legacy net.sf.liferea namespace. The problem is how tightly it is linked into the application identity especially concerning DBUS (documented API), dconf (would require active migration) and binary formats as Flatpak. I fear the effort and support work caused by this without any user facing benefit.
