### ISSUE TITLE
Toolbar keeps hiding on Pop_OS! 18.04 LTS 

### ISSUE THREAD

**Issue by saurabh2804** [lwindolf/liferea#770] opened 2020-01-11 03:56 UTC
Liferea 1.12.7. Toolbar keeps disappearing. To bring it back I have to go to Tools > Preference > GUI and check "Hide Toolbar" and then uncheck it again. The toolbar appears again. This has started happening recently. 
I have tested both on Wayland and X with the same behavior.

**Comment by Leiaz** [comment] 2020-03-08 19:58
Are you using the Header bar plugin ? Header bars are supposed to replace the menu bar and toolbar, so the plugin hides the toolbar.

**Comment by nekohayo** [comment] 2020-03-30 03:35
If @saurabh2804 has the headerbar plugin active (please confirm...) then this is a duplicate of #744, which should be about the option being completely hidden when the headerbar plugin is active.

**Comment by lwindolf** [comment] 2020-04-19 20:22
Yeah, probably a race/side effect of the switching between normal menu and headerbar.

I'm thinking about doing a poll to ask users to vote on menu vs. headerbar.

**Comment by lwindolf** [comment] 2022-10-12 00:06
Given that the headerbar plugin is not the standard way and "only" an extra bolt-on plugin I believe this inconsistency is ok. This is a trade off of allowing the header bar use case to live alongside the classic UI.

**Closed by lwindolf** 2022-10-12 00:06 UTC
