### ISSUE TITLE
Header Bar plugin

### ISSUE THREAD

**Issue by ndias** [lwindolf/liferea#644] opened 2018-05-23 21:20 UTC
When the Header Bar plugin is active, liferea doesn't remember the size of the window of liferea after restart.

**Comment by lwindolf** [comment] 2018-05-31 20:50
Reproduced.

**Comment by lwindolf** [comment] 2018-05-31 20:51
Seems like the gtk_window_set_titlebar() causes the entire window to be reinitialized.

**Comment by lwindolf** [comment] 2018-05-31 20:53
Additionally the window get smaller each launch time.

**Comment by nekohayo** [comment] 2020-03-30 03:01
I don't experience this issue on 1.12.7, should this ticket be closed?

**Comment by ndias** [comment] 2020-03-30 09:59
No, I have liferea-1.12.7 and I still have this issue.

**Comment by lwindolf** [comment] 2020-04-19 20:20
Still present in 1.13.1

I do not consider it super critical as it is an optional plugin.

At the same time I have no idea how to get rid of this nasty effect. Maybe it will be gone when the switching from normal menu to headerbar during startup is gone...

**Comment by lwindolf** [comment] 2021-04-20 16:38
@nekohayo Good idea. Closing as duplicate of #909

**Closed by lwindolf** 2021-04-20 16:38 UTC
Labels: bug, help-wanted
